### ISSUE TITLE
DEPLOYMENT.md中这里是否需要改成""

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#10]
![image](https://user-images.githubusercontent.com/11187356/80332642-f4f1d380-887d-11ea-966f-2a143c85dbdd.png)

**Comment by joyoFeng** [comment]
Yes, it gets json format issues here, we will fix right later.

**Comment by joyoFeng** [comment]
This issue has fixed, for the commit: https://github.com/LatticeX-Foundation/Rosetta/commit/3e49c35eaca53e40194b20696cd04cede4e5d6b4, I will close the issue
