### ISSUE TITLE
部署安装问题

### ISSUE THREAD

**Issue by mpmiles** [LatticeX-Foundation/Rosetta#101]
cc/python_export/_rosetta.cc:28:10: fatal error: cc/third_party/io/include/io/channel.h: No such file or directory
/Rosetta-master/cc/modules/iowrapper/include/io_wrapper.h:23:10: fatal error: io/channel.h: No such file or directory
git拉取包，各种问题，有没有大佬已经成功的留个联系方式请教一下，感谢

**Comment by yuucyf** [comment]
> cc/python_export/_rosetta.cc:28:10: fatal error: cc/third_party/io/include/io/channel.h: No such file or directory /Rosetta-master/cc/modules/iowrapper/include/io_wrapper.h:23:10: fatal error: io/channel.h: No such file or directory git拉取包，各种问题，有没有大佬已经成功的留个联系方式请教一下，感谢

请参考：https://github.com/LatticeX-Foundation/Rosetta/issues/96

**Comment by mpmiles** [comment]
@yuucyf 完美解决，非常感谢

**Comment by mpmiles** [comment]
> > cc/python_export/_rosetta.cc:28:10：致命错误：cc/third_party/io/include/io/channel.h：没有这样的文件或目录/Rosetta-master/cc/modules/iowrapper/include/io_wrapper.h :23:10: fatal error: io/channel.h: No such file or directory git拉取包，各种问题，有没有大佬已经成功的留个联系方式请教一下，谢谢
> 
> 请参考：#96

 完美解决，非常感谢，方便留个联系方式吗，邮箱啥的，如再有问题再跟您请教一下。
