### ISSUE TITLE
Rosetta现在是只能支持3方的安全计算协议？

### ISSUE THREAD

**Issue by mpmiles** [LatticeX-Foundation/Rosetta#102]
The current version integrates the secure multi-party computation protocols for 3 parties. The underlying protocols are [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Helix. They are secure in the semi-honest model with honest majority.
现版本Rosetta是只能支持3方的安全计算吗，少一方或者多一方都无法支持吗？

**Comment by xiangxiecrypto** [comment]
The underlying ZKML protocol is two-party.

**Comment by mpmiles** [comment]
> > The current version integrates the secure multi-party computation protocols for 3 parties. The underlying protocols are [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Helix. They are secure in the semi-honest model with honest majority. 现版本Rosetta是只能支持3方的安全计算吗，少一方或者多一方都无法支持吗？
> 
> 是的，目前 SecureNN 和 Helix 是三方协议。

那如果要只做两方计算或者更多方的该如何使用Rosetta，谢谢

**Comment by mpmiles** [comment]
> 底层 ZKML 协议是两方的。

请教下这个再Rosetta里如何使用呢？

**Comment by xiangxiecrypto** [comment]
> > > The current version integrates the secure multi-party computation protocols for 3 parties. The underlying protocols are [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Helix. They are secure in the semi-honest model with honest majority. 现版本Rosetta是只能支持3方的安全计算吗，少一方或者多一方都无法支持吗？
> > 
> > 
> > 是的，目前 SecureNN 和 Helix 是三方协议。
> 
> 那如果要只做两方计算或者更多方的该如何使用Rosetta，谢谢

如果在场景里面允许一个semi-honest的第三方存在，可以直接用SNN/Helix协议。Semi-honest指的只按照协议严格执行，但是不会获得数据的信息。

如果要求必须只有2方，那要等后续我们公布的新协议和算法。

**Comment by xiangxiecrypto** [comment]
> > 底层 ZKML 协议是两方的。
> 
> 请教下这个再Rosetta里如何使用呢？

Rosetta的Readme里面有使用教程，但是ZKML的场景与一般的MPC有一定的区别，要看是否能够满足要求。

**Comment by mpmiles** [comment]
> 

好的，明白

**Comment by mpmiles** [comment]
> > > > The current version integrates the secure multi-party computation protocols for 3 parties. The underlying protocols are [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Helix. They are secure in the semi-honest model with honest majority. 现版本Rosetta是只能支持3方的安全计算吗，少一方或者多一方都无法支持吗？
> > > 
> > > 
> > > 是的，目前 SecureNN 和 Helix 是三方协议。
> > 
> > 
> > 那如果要只做两方计算或者更多方的该如何使用Rosetta，谢谢
> 
> 如果在场景里面允许一个semi-honest的第三方存在，可以直接用SNN/Helix协议。Semi-honest指的只按照协议严格执行，但是不会获得数据的信息。
> 
> 如果要求必须只有2方，那要等后续我们公布的新协议和算法。

好的，了解，感谢

**Comment by mpmiles** [comment]
> > > 底层 ZKML 协议是两方的。
> > 
> > 
> > 请教下这个再Rosetta里如何使用呢？
> 
> Rosetta的Readme里面有使用教程，但是ZKML的场景与一般的MPC有一定的区别，要看是否能够满足要求。

您说的这个是不是readme里ZKP那个例子？

**Comment by xiangxiecrypto** [comment]
> > > > 底层 ZKML 协议是两方的。
> > > 
> > > 
> > > 请教下这个再Rosetta里如何使用呢？
> > 
> > 
> > Rosetta的Readme里面有使用教程，但是ZKML的场景与一般的MPC有一定的区别，要看是否能够满足要求。
> 
> 您说的这个是不是readme里ZKP那个例子？

是的

**Comment by mpmiles** [comment]
> > > > > 底层 ZKML 协议是两方的。
> > > > 
> > > > 
> > > > 请教下这个再Rosetta里如何使用呢？
> > > 
> > > 
> > > Rosetta的Readme里面有使用教程，但是ZKML的场景与一般的MPC有一定的区别，要看是否能够满足要求。
> > 
> > 
> > 您说的这个是不是readme里ZKP那个例子？
> 
> 是的

好的，感谢！！！

**Comment by ludeen007** [comment]
> > > > The current version integrates the secure multi-party computation protocols for 3 parties. The underlying protocols are [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Helix. They are secure in the semi-honest model with honest majority. 现版本Rosetta是只能支持3方的安全计算吗，少一方或者多一方都无法支持吗？
> > > 
> > > 
> > > 是的，目前 SecureNN 和 Helix 是三方协议。
> > 
> > 
> > 那如果要只做两方计算或者更多方的该如何使用Rosetta，谢谢
> 
> 如果在场景里面允许一个semi-honest的第三方存在，可以直接用SNN/Helix协议。Semi-honest指的只按照协议严格执行，但是不会获得数据的信息。
> 
> 如果要求必须只有2方，那要等后续我们公布的新协议和算法。

你好，请问后续有计划实现只有2方的协议和算法吗？如果有的话，大概是什么时间点？
