### ISSUE TITLE
ERROR:Rosetta:Protocol, `Mystique`, is not supported! dueing ZKP sample code test

### ISSUE THREAD

**Issue by junjiequ123** [LatticeX-Foundation/Rosetta#104]
Source code: 
https://github.com/LatticeX-Foundation/Rosetta/blob/master/example/tutorials/code/rosetta_demo_zkp.py

Command line:
> python3 rosetta_demo_zkp.py --party_id=0
(note: run party 0, 1, 2 seperately)

Error details:
==================
Create IO ok, task id:
ERROR:Rosetta:Protocol, `Mystique`, is not supported!
Traceback (most recent call last):
  File "zkpTest.py", line 8, in <module>
    rtt.activate("Mystique")
  File "/home/junjiequ/.local/lib/python3.6/site-packages/latticex/rosetta/controller/protocol_api.py", line 80, in activate
    protocol_name + "', is not supported yet!")
ValueError: The protocol you chose: 'Mystique', is not supported yet!

**Comment by xiaojiqing** [comment]
It is very likely that you compiled rosetta without enabling zk. Try to compile rosetta with --enable-protocol-zk. In addition to this, you should run the example with option --cfgfile CONFIG_ZKP.json together with option --party_id=<PARTY_ID>. <PARTY_ID> is limited to be 0 or 1. The config file default to be CONFIG.json can only be used in protocols having 3 parties.

**Comment by junjiequ123** [comment]
thanks, it works after re-install rosetta.  

1. there are a few independent protocols can be switch on by --enable-protocol-*, refer to rosetta.sh for details.
rosetta.sh:    echo "       --enable-protocol-mpc-securenn     [OFF] Secure Multi-party Computation (base on SecureNN)"
rosetta.sh:    echo "       --enable-protocol-mpc-helix        [OFF] Secure Multi-party Computation (base on Helix)"
rosetta.sh:    echo "       --enable-protocol-zk               [OFF] Zero-Knowledge Proof"

I have enabled them all, then re-installed rosetta

2. also there are many config files for reference, CONFIG_ZKP.json is the one used
./cc/conf/CONFIG.json
./example/contrib/CONFIG.json
./example/millionaire/CONFIG.json
./example/tutorials/code/CONFIG.json
./example/tutorials/code/CONFIG_ZKP.json   <---- this is the one
./example/zkp_lr/CONFIG.json
./example/zkp_resnet/rtt-predict/CONFIG.json
./example/zkp_resnet/rtt-predict/CONFIG_LAN.json
./python/latticex/rosetta/controller/test/CONFIG.json
./python/latticex/rosetta/secure/data/ops/test_cases/CONFIG.json
./python/latticex/rosetta/secure/utils/test_cases/CONFIG.json
./python/latticex/rosetta/test/dpass/CONFIG.json
./python/latticex/rosetta/test/grads_ops/CONFIG.json
./python/latticex/rosetta/test/multi-task/CONFIG.json
./python/latticex/rosetta/test/multi_data_source/CONFIG.json
./python/latticex/rosetta/test/multi_data_source/CONFIG.json__
./python/latticex/rosetta/test/single-task/CONFIG.json
./python/latticex/rosetta/test/single-task/misc/CONFIG.json
./python/latticex/rosetta/test/spass/CONFIG.json

3. continued my test, unfortunately run into another strange error, recording here for reference. try to debug it

    import latticex.rosetta as rtt
  File "/home/junjiequ/.local/lib/python3.6/site-packages/latticex/rosetta/__init__.py", line 24, in <module>
    from latticex.rosetta.controller.common_util import rtt_get_logger
  File "/home/junjiequ/.local/lib/python3.6/site-packages/latticex/rosetta/controller/__init__.py", line 20, in <module>
    from latticex.rosetta.controller.backend_handler import *
  File "/home/junjiequ/.local/lib/python3.6/site-packages/latticex/rosetta/controller/backend_handler.py", line 19, in <module>
    from latticex.rosetta.controller.controller_base_ import _rtt
  File "/home/junjiequ/.local/lib/python3.6/site-packages/latticex/rosetta/controller/controller_base_.py", line 27, in <module>
    import latticex._rosetta as _rst
ImportError: /home/junjiequ/.local/lib/python3.6/site-packages/latticex/libzkp-mystique.so: undefined symbol: _ZN11CheatRecord7messageE

**Comment by xiaojiqing** [comment]
This bug had been fixed in the latest commit with commit id 90bce72fd34c0f6657a7e6e06ba90f9565016e25. You ought to fetch the latest code and compile again.
