### ISSUE TITLE
Rosetta可以支持基于Bert的文本分类和事件抽取任务吗？

### ISSUE THREAD

**Issue by cuiMidAutumn** [LatticeX-Foundation/Rosetta#106]
Rosetta可以加密处理非数字类型数据吗？如文本数据，然后进一步进行下游的NLP相关任务

**Comment by xiangxiecrypto** [comment]
这个取决于明文的时候对这些类型的编码，以及要处理的操作。
你可以用简单的API先试一下，完整的NLP相关的模型应该还没有支持。
如果模型中的操作可以分解成已经支持的算子，则可以自行组合成模型。
如果算子不支持，则需要额外开发。
