### ISSUE TITLE
AttributeError: module 'latticex.rosetta' has no attribute 'set_saver_model'

### ISSUE THREAD

**Issue by cuiMidAutumn** [LatticeX-Foundation/Rosetta#110]
您好，运行线性回归脚本时遇到如图的报错，请问是什么原因呢，版本问题吗，我是通过pip3 install 安装的
![image](https://user-images.githubusercontent.com/43536013/163424720-0deed29c-bf81-4649-8160-56198279d119.png)

**Comment by yuucyf** [comment]
> 您好，运行线性回归脚本时遇到如图的报错，请问是什么原因呢，版本问题吗，我是通过pip3 install 安装的 ![image](https://user-images.githubusercontent.com/43536013/163424720-0deed29c-bf81-4649-8160-56198279d119.png)

您应该是直接使用 pip3 install ，然后使用 github 上的 example 验证吧？这会存在版本不一致问题。
因为使用 pip3 安装还存在一些问题需优化，故最新版本没有制作 pip3 包，请暂不要使用。
解决方式是卸载当前版本使用源码安装即可。

**Comment by cuiMidAutumn** [comment]
请问在docker容器中按照部署指南的指令 为什么安装不成功呢？其他环境要求都满足

![image](https://user-images.githubusercontent.com/43536013/163541607-9fee110f-dd81-4f3a-8b8e-1b813506c187.png)

**Comment by yuucyf** [comment]
> 请问在docker容器中按照部署指南的指令 为什么安装不成功呢？其他环境要求都满足
> 
> ![image](https://user-images.githubusercontent.com/43536013/163541607-9fee110f-dd81-4f3a-8b8e-1b813506c187.png)

应该是 rosetta 的 submodule 没有 update 成功。

**Comment by 1078158952** [comment]
> 请问在docker容器中按照部署指南的指令 为什么安装不成功呢？其他环境要求都满足
> 
> ![image](https://user-images.githubusercontent.com/43536013/163541607-9fee110f-dd81-4f3a-8b8e-1b813506c187.png)

我也遇到了这个问题git clone --recurse https://github.com/LatticeX-Foundation/Rosetta.git 的时候需要添加 --recurse  非常重要
