### ISSUE TITLE
部署Rosetta后运行示例出错

### ISSUE THREAD

**Issue by Averryjj** [LatticeX-Foundation/Rosetta#112]
按照教程部署后，在运行百万富翁示例时，可以出现运行结果，但是p1和p2f方也会有错误：
<img width="713" alt="企业微信截图_16510390696865" src="https://user-images.githubusercontent.com/89241701/165451040-6c5440d2-3a18-4111-a797-c6fbc2bb9da5.png">
运行逻辑回归示例时，出现：
<img width="630" alt="企业微信截图_16510392005759" src="https://user-images.githubusercontent.com/89241701/165451346-261d486e-f4cb-4378-99b5-b7fda4139e25.png">
请教下，各位专家，怎么解决？
安装环境：虚拟机ubuntu18.04,python3.7,8核12G

**Comment by yuucyf** [comment]
> 按照教程部署后，在运行百万富翁示例时，可以出现运行结果，但是p1和p2f方也会有错误： <img alt="企业微信截图_16510390696865" width="713" src="https://user-images.githubusercontent.com/89241701/165451040-6c5440d2-3a18-4111-a797-c6fbc2bb9da5.png"> 运行逻辑回归示例时，出现： <img alt="企业微信截图_16510392005759" width="630" src="https://user-images.githubusercontent.com/89241701/165451346-261d486e-f4cb-4378-99b5-b7fda4139e25.png"> 请教下，各位专家，怎么解决？ 安装环境：虚拟机ubuntu18.04,python3.7,8核12G

从你提供的第二个截图发现在初始化协议的时候程序已经异常了，执行程序不会出现结果的，是不是日志提取错了，时间看起来也不太一致，不同的节点时间相差有几分钟，应该是不同的任务。
另外怀疑你本地机器上有的节点进程没有退出，可以尝试先把未退出的节点 kill 后，重新执行一遍试试。

**Comment by Averryjj** [comment]
第一张图是运行的百万富翁的结果截图，第二种是运行的逻辑回归的结果截图，是不同任务的一方的节点日志截图。
我尝试过kill后运行，但是还是出现核心已转储的问题
