### ISSUE TITLE
有没有多方隐私排序算法？

### ISSUE THREAD

**Issue by Averryjj** [LatticeX-Foundation/Rosetta#113]
两方使用多方安全计算进行排序，sort算子有计划支持吗？

**Comment by YuanFengChen** [comment]
> 两方使用多方安全计算进行排序，sort算子有计划支持吗？

三方 sort 算子我们已经实现了，目前还暂未开源。

**Comment by Averryjj** [comment]
好的，谢谢，目前Rosetta只开源v1.0版本，后续升级版本还有开源计划吗？

**Comment by yuucyf** [comment]
> 好的，谢谢，目前Rosetta只开源v1.0版本，后续升级版本还有开源计划吗？

未来版本还是会继续开源，但是具体的日程还在计划中。
