### ISSUE TITLE
使用rosetta跑了一个简单的逻辑回归后内存泄漏了

### ISSUE THREAD

**Issue by Zoey969** [LatticeX-Foundation/Rosetta#115]
操作系统：ubuntu18.04
python版本：3.6
问题描述：之前运行过rosetta中的线性回归和逻辑回归的demo都没有问题，接着自己写了一个简单的逻辑回归（已在明文中测试过没有错误），可能是里面用到了relu函数，大致是5分钟跑完一个epoch，于是我退出进程改为sigmoid函数了，至此再使用rosetta跑代码都显示内存泄漏了。请问我该怎么解决这个问题

**Comment by YuanFengChen** [comment]
> 操作系统：ubuntu18.04 python版本：3.6 问题描述：之前运行过rosetta中的线性回归和逻辑回归的demo都没有问题，接着自己写了一个简单的逻辑回归（已在明文中测试过没有错误），可能是里面用到了relu函数，大致是5分钟跑完一个epoch，于是我退出进程改为sigmoid函数了，至此再使用rosetta跑代码都显示内存泄漏了。请问我该怎么解决这个问题

可否把你自己写的逻辑回归代码贴上来，另外把你的操作步骤也简单说明一下可好。

**Comment by Zoey969** [comment]
打开三个终端，python xxx.py --party=x`
import latticex.rosetta as rtt
import os
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


np.set_printoptions(suppress=True)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# np.random.seed(0)
rtt.activate("SecureNN")
mpc_player_id = rtt.py_protocol_handler.get_party_id()

# 创建占位符
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# 创建变量
# tf.random_normal([1])返回一个符合正态分布的随机数

# w = tf.Variable(rtt.private_input(0,tf.random_normal([1], name='weight')))
w = tf.Variable(tf.random_normal([1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

y_predict = tf.sigmoid(tf.multiply(X, w) + b)
# y_predict = tf.nn.relu(tf.multiply(X, w) + b)
num_samples = 400
cost = tf.reduce_sum(tf.square(y_predict - Y)) / num_samples
# cost = tf.reduce_mean(tf.square(y_predict - Y)) / num_samples

# 学习率
lr = 0.01
# optimizer = tf.train.AdamOptimizer().minimize(cost)
optimizer = tf.train.GradientDescentOptimizer(lr).minimize(cost)
# 创建session 并初始化所有变量
num_epoch = 50
cost_accum = []
cost_prev = 0
# np.linspace（）创建agiel等差数组，元素个素为num_samples
xs = np.linspace(-5, 5, num_samples)
ys = np.sin(xs) + np.random.normal(0, 0.01, num_samples)

init = tf.compat.v1.global_variables_initializer()

with tf.Session() as sess:
    # 初始化所有变量
    sess.run(init)
    # 开始训练
    for epoch in range(num_epoch):
        for x, y in zip(xs, ys):
            sess.run(optimizer, feed_dict={X: x, Y: y})
        train_cost = sess.run(cost, feed_dict={X: x, Y: y})
        cost_accum.append(train_cost)
        print("train_cost is:", str(train_cost))

        # 当误差小于10-6时 终止训练
        # if np.abs(cost_prev - train_cost) < 1e-6:
        #     break
        # 保存最终的误差
        cost_prev = train_cost
    pred_y = sess.run(y_predict,feed_dict={X: x, Y: y})
    print("pred_y=",pred_y)
    #设定得到明文输出的服务器为P0和P1
    a_and_b_can_get_plain = 0b011
    # Get the result of Rosetta matmul
    print('plaintext Y_pred result:', sess.run(
        rtt.SecureReveal(pred_y, a_and_b_can_get_plain)))
# 画图 画出每一轮训练所有样本之后的误差
# plt.plot(range(len(cost_accum)), cost_accum, 'r')
# plt.title('Logic Regression Cost Curve')
# plt.xlabel('epoch')
# plt.ylabel('cost')
# plt.show()`

**Comment by Zoey969** [comment]
打开三个终端，python xxx.py --party=x
`
import latticex.rosetta as rtt
import os
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


np.set_printoptions(suppress=True)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

rtt.activate("SecureNN")
mpc_player_id = rtt.py_protocol_handler.get_party_id()
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
w = tf.Variable(tf.random_normal([1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

y_predict = tf.sigmoid(tf.multiply(X, w) + b)

num_samples = 400
cost = tf.reduce_sum(tf.square(y_predict - Y)) / num_samples


lr = 0.01
optimizer = tf.train.GradientDescentOptimizer(lr).minimize(cost)
num_epoch = 50
cost_accum = []
cost_prev = 0
xs = np.linspace(-5, 5, num_samples)
ys = np.sin(xs) + np.random.normal(0, 0.01, num_samples)
init = tf.compat.v1.global_variables_initializer()

with tf.Session() as sess:

    sess.run(init)
 
    for epoch in range(num_epoch):
        for x, y in zip(xs, ys):
            sess.run(optimizer, feed_dict={X: x, Y: y})
        train_cost = sess.run(cost, feed_dict={X: x, Y: y})
        cost_accum.append(train_cost)
        print("train_cost is:", str(train_cost))
        cost_prev = train_cost
    pred_y = sess.run(y_predict,feed_dict={X: x, Y: y})
    print("pred_y=",pred_y)
    
    a_and_b_can_get_plain = 0b011
    
    print('plaintext Y_pred result:', sess.run(
        rtt.SecureReveal(pred_y, a_and_b_can_get_plain)))
`

**Comment by YuanFengChen** [comment]
> 打开三个终端，python xxx.py --party=x ` import latticex.rosetta as rtt import os import tensorflow as tf import numpy as np import matplotlib.pyplot as plt
> 
> np.set_printoptions(suppress=True)
> 
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
> 
> rtt.activate("SecureNN") mpc_player_id = rtt.py_protocol_handler.get_party_id() X = tf.placeholder(tf.float32) Y = tf.placeholder(tf.float32) w = tf.Variable(tf.random_normal([1], name='weight')) b = tf.Variable(tf.random_normal([1], name='bias'))
> 
> y_predict = tf.sigmoid(tf.multiply(X, w) + b)
> 
> num_samples = 400 cost = tf.reduce_sum(tf.square(y_predict - Y)) / num_samples
> 
> lr = 0.01 optimizer = tf.train.GradientDescentOptimizer(lr).minimize(cost) num_epoch = 50 cost_accum = [] cost_prev = 0 xs = np.linspace(-5, 5, num_samples) ys = np.sin(xs) + np.random.normal(0, 0.01, num_samples) init = tf.compat.v1.global_variables_initializer()
> 
> with tf.Session() as sess:
> 
> ```
> sess.run(init)
> 
> for epoch in range(num_epoch):
>     for x, y in zip(xs, ys):
>         sess.run(optimizer, feed_dict={X: x, Y: y})
>     train_cost = sess.run(cost, feed_dict={X: x, Y: y})
>     cost_accum.append(train_cost)
>     print("train_cost is:", str(train_cost))
>     cost_prev = train_cost
> pred_y = sess.run(y_predict,feed_dict={X: x, Y: y})
> print("pred_y=",pred_y)
> 
> a_and_b_can_get_plain = 0b011
> 
> print('plaintext Y_pred result:', sess.run(
>     rtt.SecureReveal(pred_y, a_and_b_can_get_plain)))
> ```
> 
> `

程序最后调用一下：
```python
rtt.deactivate()
```

**Comment by Zoey969** [comment]
![image](https://user-images.githubusercontent.com/107387594/174240190-5b7cbf67-e123-4330-8a17-55786b439e14.png)
现在运行的时候会报这个错误

**Comment by YuanFengChen** [comment]
> ![image](https://user-images.githubusercontent.com/107387594/174240190-5b7cbf67-e123-4330-8a17-55786b439e14.png) 现在运行的时候会报这个错误

这种情况应该是配置错了，或者路径不对，你 checked 日志文件上是不是有：
`Fail to load or parse your config... ` 这样的错误信息呢？

可以参考 Tutorials 上如何运行测试用例。

**Comment by Zoey969** [comment]
您好，内存泄漏问题已经解决了，但我发现明文下能够运行的代码（如下）部署到rosetta中后sess.run()是不运行的，请问您知道问题出在哪里吗？
```
import tensorflow as tf
import numpy as np
import os
import latticex.rosetta as rtt
import matplotlib.pyplot as plt

np.set_printoptions(suppress=True)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

np.random.seed(0)

rtt.activate("SecureNN")
mpc_player_id = rtt.py_protocol_handler.get_party_id()

def add_layer(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))  # 正态分布
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)  # 1行，out_size列，初始值不推荐为0，所以加上0.1
    Wx_plus_b = tf.matmul(inputs, Weights) + biases  # Weights*x+b的初始化值，也是未激活的值
    # 激活
    if activation_function is None:
        # 如果没有设置激活函数，，则直接把当前信号原封不动的传递出去
        outputs = Wx_plus_b
    else:
        # 如果设置了激活函数，则由此激活函数对信号进行传递或抑制
        outputs = activation_function(Wx_plus_b)
    return outputs

x = np.linspace(-1, 1, 300)[:, np.newaxis]  # np.linspace在指定间隔内返回均匀间隔数字

noise = np.random.normal(0, 0.05, x.shape)
y = np.square(x) - 0.5 + noise
x_data,y_data = rtt.PrivateDataset(data_owner=(0, 1),label_owner=0).load_data(x, y)

xs = tf.placeholder(tf.float64, [None, 1])
ys = tf.placeholder(tf.float64, [None, 1])

l1 = add_layer(xs, 1, 10, activation_function=tf.nn.relu)

prediction = add_layer(l1, 10, 1, activation_function=None)


loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction), reduction_indices=[1]))


train = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for i in range(1000):  # 学习1000次
        print("@" * 100)
        sess.run(train, feed_dict={xs: x_data, ys: y_data})
        print("8" * 100)
        if i % 50 == 0:
            print("$"*100)
            Loss = sess.run(loss, feed_dict={xs: x_data, ys: y_data})
            print("epoch=",i,"\tLoss=",Loss)

    # predict
    Y_pred = sess.run(train, feed_dict={xs: x_data, ys: y_data})
    real_Y_pred = rtt.SecureReveal(Y_pred)
    # print('plaintext result:', real_Y_pred)
    print("Y_pred:", Y_pred)
    # Set only party a and b can get plain result
    a_and_b_can_get_plain = 0b011
    # Get the result of Rosetta matmul
    print('plaintext Y_pred result:', sess.run(
        rtt.SecureReveal(Y_pred, a_and_b_can_get_plain)))

print(rtt.get_perf_stats(True))
rtt.deactivate()
```

另，这是异常
tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.

**Comment by YuanFengChen** [comment]
> 您好，内存泄漏问题已经解决了，但我发现明文下能够运行的代码（如下）部署到rosetta中后sess.run()是不运行的，请问您知道问题出在哪里吗？
> 
> ```
> import tensorflow as tf
> import numpy as np
> import os
> import latticex.rosetta as rtt
> import matplotlib.pyplot as plt
> 
> np.set_printoptions(suppress=True)
> 
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
> 
> np.random.seed(0)
> 
> rtt.activate("SecureNN")
> mpc_player_id = rtt.py_protocol_handler.get_party_id()
> 
> def add_layer(inputs, in_size, out_size, activation_function=None):
>     Weights = tf.Variable(tf.random_normal([in_size, out_size]))  # 正态分布
>     biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)  # 1行，out_size列，初始值不推荐为0，所以加上0.1
>     Wx_plus_b = tf.matmul(inputs, Weights) + biases  # Weights*x+b的初始化值，也是未激活的值
>     # 激活
>     if activation_function is None:
>         # 如果没有设置激活函数，，则直接把当前信号原封不动的传递出去
>         outputs = Wx_plus_b
>     else:
>         # 如果设置了激活函数，则由此激活函数对信号进行传递或抑制
>         outputs = activation_function(Wx_plus_b)
>     return outputs
> 
> x = np.linspace(-1, 1, 300)[:, np.newaxis]  # np.linspace在指定间隔内返回均匀间隔数字
> 
> noise = np.random.normal(0, 0.05, x.shape)
> y = np.square(x) - 0.5 + noise
> x_data,y_data = rtt.PrivateDataset(data_owner=(0, 1),label_owner=0).load_data(x, y)
> 
> xs = tf.placeholder(tf.float64, [None, 1])
> ys = tf.placeholder(tf.float64, [None, 1])
> 
> l1 = add_layer(xs, 1, 10, activation_function=tf.nn.relu)
> 
> prediction = add_layer(l1, 10, 1, activation_function=None)
> 
> 
> loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction), reduction_indices=[1]))
> 
> 
> train = tf.train.GradientDescentOptimizer(0.1).minimize(loss)
> 
> init = tf.global_variables_initializer()
> 
> with tf.Session() as sess:
>     sess.run(init)
>     for i in range(1000):  # 学习1000次
>         print("@" * 100)
>         sess.run(train, feed_dict={xs: x_data, ys: y_data})
>         print("8" * 100)
>         if i % 50 == 0:
>             print("$"*100)
>             Loss = sess.run(loss, feed_dict={xs: x_data, ys: y_data})
>             print("epoch=",i,"\tLoss=",Loss)
> 
>     # predict
>     Y_pred = sess.run(train, feed_dict={xs: x_data, ys: y_data})
>     real_Y_pred = rtt.SecureReveal(Y_pred)
>     # print('plaintext result:', real_Y_pred)
>     print("Y_pred:", Y_pred)
>     # Set only party a and b can get plain result
>     a_and_b_can_get_plain = 0b011
>     # Get the result of Rosetta matmul
>     print('plaintext Y_pred result:', sess.run(
>         rtt.SecureReveal(Y_pred, a_and_b_can_get_plain)))
> 
> print(rtt.get_perf_stats(True))
> rtt.deactivate()
> ```
> 
> 另，这是异常 tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.

代码写的有问题：
```python
xs = tf.placeholder(tf.float64, [None, 1])
```
这个 xs shape 是 [?, 1]

而：
```python
x_data,y_data = rtt.PrivateDataset(data_owner=(0, 1),label_owner=0).load_data(x, y)  #要根据使用来确定是特征对齐还是样本对齐，是有参数可以调整的。
```
x_data 这里的 shape 是 [300, 2]

然后使用的时候：
```python
sess.run(train, feed_dict={xs: x_data, ys: y_data}) 
```
x_data feed to xs ， x_data 和 xs 的 shape 都不相同，肯定不能正常 feed ，应该会报错：
ValueError: Cannot feed value of shape (300, 2) for Tensor xxx, which has shape '(?, 1)'
