### ISSUE TITLE
Issue with compilation: 'x86_64-linux-gnu-g++'

### ISSUE THREAD

**Issue by jack-clone** [LatticeX-Foundation/Rosetta#117]
I'm trying to follow the installation steps but  after running
`./rosetta.sh compile --enable-protocol-mpc-securenn`
I get the following error at the end of compilation:
`collect2: error: ld returned 1 exit status
error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
`
The full error log also contains some c++ compilation errors I believe. However, I'm pretty sure my cmake is up to date? Any help would be appreciated.

Full error log:
[error.txt](https://github.com/LatticeX-Foundation/Rosetta/files/9023078/error.txt)

**Comment by YuanFengChen** [comment]
> 

Just because cmake is up to date does not mean that the C++ toolchain is also up to date.

Error messages are more obvious, such as：
#error This compiler appears to be too old to be supported by Eigen
update the C++ compilation toolchain version to try again.

**Comment by jack-clone** [comment]
Thank you, that fixed the first command. However, when I run 
```./rosetta.sh install```
I now have the following message:
```
WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
run_rosetta_install_python.
```
I looked at #89 but I am not sure what I should be looking for in `cc/thirdparty/spdlog`. 

Am I missing a wheels package or something? I am not sure what the `dist/*.whl` is.

**Comment by YuanFengChen** [comment]
> Thank you, that fixed the first command. However, when I run `./rosetta.sh install` I now have the following message:
> 
> ```
> WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
> ERROR: *.whl is not a valid wheel filename.
> run_rosetta_install_python.
> ```
> 
> I looked at #89 but I am not sure what I should be looking for in `cc/thirdparty/spdlog`.
> 
> Am I missing a wheels package or something? I am not sure what the `dist/*.whl` is.

**it means no compilation success.**

You need to get down the submodules that dependent on this project.
Use the following commands：
git submodule init
git submodule update

Please refer to #96

**Comment by jack-clone** [comment]
Unfortunately I'm still encountering the same error after running the two commands in the root directory of the project. 

I checked the `.gitmodules` file and the corresponding file locations and it seems the submodules are already installed. Is there something else I can try?

**Comment by YuanFengChen** [comment]
> Unfortunately I'm still encountering the same error after running the two commands in the root directory of the project.
> 
> I checked the `.gitmodules` file and the corresponding file locations and it seems the submodules are already installed. Is there something else I can try?

You can check the compile output log to make sure there are no errors.

**Comment by jack-clone** [comment]
When you say the "compile output log" do you mean just redirecting all the standard error output to a text file? 

I ran ` ./rosetta.sh compile --enable-protocol-mpc-securenn` again and it seems I still have 
```
#error This compiler appears to be too old to be supported by Eigen
update the C++ compilation toolchain version to try again.
```
despite updating my gcc and g++ versions to versions 11.0.1. Do you have any ideas on what I should try to do next?

**Comment by YuanFengChen** [comment]
> When you say the "compile output log" do you mean just redirecting all the standard error output to a text file?
> 
> I ran ` ./rosetta.sh compile --enable-protocol-mpc-securenn` again and it seems I still have
> 
> ```
> #error This compiler appears to be too old to be supported by Eigen
> update the C++ compilation toolchain version to try again.
> ```
> 
> despite updating my gcc and g++ versions to versions 11.0.1. Do you have any ideas on what I should try to do next?

Check tensorflow version is 1.14.0？rosetta currently supports tensorflow version is 1.14.0.
