### ISSUE TITLE
部署Rosetta的过程中出现这样的错误如何解决呢？

### ISSUE THREAD

**Issue by CCCarrot** [LatticeX-Foundation/Rosetta#118]
执行命令“./rosetta.sh compile --enable-protocol-mpc-securenn && ./rosetta.sh install”后出现如下的错误，请问这是哪里出错了呢？
![image](https://user-images.githubusercontent.com/38489942/177459364-25eb8bb3-3719-4a0a-9276-fbbadeeaf554.png)

**Comment by YuanFengChen** [comment]
> 执行命令“./rosetta.sh compile --enable-protocol-mpc-securenn && ./rosetta.sh install”后出现如下的错误，请问这是哪里出错了呢？ ![image](https://user-images.githubusercontent.com/38489942/177459364-25eb8bb3-3719-4a0a-9276-fbbadeeaf554.png)

应该是编译时出现错误了，可以检查一下编译输出日志看下是否存在一些编译 Error 。

**Comment by CCCarrot** [comment]
> 

检查过后没能找到问题的源头，最后新建了一个虚拟机从头配置之后可以正常编译了
