### ISSUE TITLE
安装Rosetta时报错

### ISSUE THREAD

**Issue by zhou-pz** [LatticeX-Foundation/Rosetta#122]
命令：
cd Rosetta && ./rosetta.sh compile --enable-protocol-mpc-securenn && ./rosetta.sh install

报错：
/home/zhou/code/Rosetta/cc/tf/rttops/convert.cc:18:10: fatal error: tensorflow/core/framework/op.h: 没有那个文件或目录
 #include "tensorflow/core/framework/op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
...
WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.

貌似是tensorflow的问题，但是执行 python3 -c 'import tensorflow as tf;print(tf.__version__)'，可以打印tensorflow版本号。

**Comment by xiaozeplus** [comment]
您好，我也遇到了相同的问题，TensorFlow是二进制安装的：`pip3 install tensorflow==1.14.0 --user`，请问这个问题解决了吗？
是否需要编译TensorFlow源码安装呢？

**Comment by joyoFeng** [comment]
请参考： https://github.com/LatticeX-Foundation/Rosetta/blob/master/doc/DEPLOYMENT.md 进行安装搭建
