### ISSUE TITLE
404 Not Found: 在DEPLOYMENT.md，当我点击example/millionaire的链接，或者直接执行wget指令时，都会出现404错误。

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#16]
![image](https://user-images.githubusercontent.com/11187356/80614537-25e62a00-8a71-11ea-9c69-7a7eea1e66d0.png)
![image](https://user-images.githubusercontent.com/11187356/80614911-9e4ceb00-8a71-11ea-8549-45a8cca57c78.png)
![image](https://user-images.githubusercontent.com/11187356/80615095-d81df180-8a71-11ea-8903-c4e0916c0bed.png)

**Comment by vingstar** [comment]
Well, this seems to be caused by our carelessness about the branch names in GitHub. It should be 
wget https://github.com/LatticeX-Foundation/Rosetta**/tree/master/**example/millionaire/millionaire.py. We will fix this issue in our document soon.
Thank you again.
