### ISSUE TITLE
Blocked here for more than half an hour, when one of nodes installed rosetta, using "cd Rosetta && bash compile_and_test_all.sh"

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#17]
![image](https://user-images.githubusercontent.com/11187356/80619460-4f09b900-8a77-11ea-9bbf-7022ec5aaed5.png)

**Comment by vingstar** [comment]
This may be caused by the incomplete exit of last execution, which may still be hung up in the background. So please try to run the `sudo kill.sh` in the top directory of this repository, and then continue your job.
Please let me know if this dose not work for you.

**Comment by changjiangbailang** [comment]
netstat -ap | grep 32000
netstat -ap | grep 32001
netstat -ap | grep 32002

and then，kill all process about “./protocol_mp”，
it OK
