### ISSUE TITLE
miss a 't', it may be "certs/server-nopass.cert"

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#18]
![image](https://user-images.githubusercontent.com/11187356/80671726-55328080-8add-11ea-98b0-a152fbce8702.png)

**Comment by changjiangbailang** [comment]
![image](https://user-images.githubusercontent.com/11187356/80671909-ca05ba80-8add-11ea-8e8b-c4ebd4e98484.png)

**Comment by vingstar** [comment]
Thank you for finding this typo, we will fix it soon.
