### ISSUE TITLE
loadXY()  miss  parameter "header=None"

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#20]
在example/tutorials/code的rtt-logistic_regression.py中，如下图红框的地方，加载数据时，少了参数”header=None"，因为加载的数据集无表头。应改为“real_X, real_Y = rtt.MpcDataSet(label_owner=0).load_XY(file_x, file_y, header=None)。
![image](https://user-images.githubusercontent.com/11187356/82201603-36cce180-9933-11ea-98c8-23eb22e72657.png)

在example/tutorials/code文件夹下的其他文件，也有此问题。

**Comment by vingstar** [comment]
Thank you for your earnest code review! We will fix this in this week.
