### ISSUE TITLE
Got stuck at rtt.activate("SecureNN")

### ISSUE THREAD

**Issue by lfxx** [LatticeX-Foundation/Rosetta#32]
执行python rtt-millionaire-console.py，运行到这一句会卡住无法往下执行

**Comment by vingstar** [comment]
Hi，lfxx，
欢迎体验Rosetta， rtt-millionaire-console.py这个例子用于让用户通过console输入的方式来体验Rosetta的基本用法。
请问是否是按照介绍的方式，在单机的三个界面中分别执行:
python rtt-millionaire-console.py --party_id=0
和
python rtt-millionaire-console.py --party_id=1
和
python rtt-millionaire-console.py --party_id=2 了呢？
如果是的化，应该很会的在P0\P1的界面会跳出提示让你输入私有“财富值的”，例如：
![image](https://user-images.githubusercontent.com/3355765/89099864-f6a2d880-d424-11ea-84ea-fb855c7d919b.png)

**Comment by vingstar** [comment]
Hi @lfxx,
Please let us know whether our solution works for you. 
I will assume it works for you and close this issue in 7 days if there is no feedback from you.
You are welcome to ask any problems in your later usage. Have fun with Rosetta.
