### ISSUE TITLE
多次调用active与deactive后，导致某一方出错

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#33]
将rosetta封装成一个服务，多次发起请求，会多次调用active与deactive。第一次，计算是可成功，但是多次调用之后，某一方(一般是P1方)会出现如下的错误。请看看是什么问题，谢谢。
![image](https://user-images.githubusercontent.com/11187356/89166212-4233be80-d5ac-11ea-852a-0fa4542d1186.png)

**Comment by ujnss** [comment]
Hi @changjiangbailang,  
这个问题是由于关闭链接(deactivate)与重新打开链接(activate)之间时间隔间太短所引起的BUG。现已修复，请参考 [Fix SSL_do_handshake error](https://github.com/LatticeX-Foundation/Rosetta/tree/13b042d22a75025cf0d4de880cdae3d1c11c66bf)。

**Comment by changjiangbailang** [comment]
Thank you,  I will try it.

**Comment by vingstar** [comment]
Hi @changjiangbailang ,
Please let us know whether our solution works for you.
I will assume it works for you and close this issue in 7 days if there is no feedback from you.
You are welcome to ask any problems in your later usage. Have fun with Rosetta.
