### ISSUE TITLE
ssl writeImpl error:0

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#37]
![image](https://user-images.githubusercontent.com/11187356/92693482-4a83d400-f378-11ea-8ff8-3586c02503df.png)
当我使用Rosetta 0.2.1进行LR训练时，碰到ssl writeImpl error:0问题，导致训练无法完成。

**Comment by vingstar** [comment]
@changjiangbailang  你好，
请问这个问题在最新版本下还存在吗？

**Comment by vingstar** [comment]
Hi @changjiangbailang, 
I will close this issue. And if the same problem occurs again, you may reopen it.
Thanks.
