### ISSUE TITLE
High memory usage with large input datasets

### ISSUE THREAD

**Issue by vingstar** [LatticeX-Foundation/Rosetta#40]
In Rosetta v0.2.1,  it seems to occupy much memory when a large private data set is used. This can be an issue for some application, and should be addressed.

**Comment by yuucyf** [comment]
> In Rosetta v0.2.1, it seems to occupy much memory when a large private data set is used. This can be an issue for some application, and should be addressed.

It is fixed in Rosetta v0.3.0, you can see the following example file for more details.
[](https://github.com/LatticeX-Foundation/Rosetta/blob/master/example/tutorials/code/rtt-ds-lr.py)

**Comment by vingstar** [comment]
@yuucyf , Great! 
 I will close this issue ASAP

**Comment by vingstar** [comment]
issue addressed.
