### ISSUE TITLE
安装卡住

### ISSUE THREAD

**Issue by huajinghua** [LatticeX-Foundation/Rosetta#42]
[ 68%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/polynomials.cpp.o
[ 76%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/sigmoid.cpp.o
[ 68%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/reduce.cpp.o
[ 68%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/opsets.cpp.o
[ 72%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/ParallelAESObject.cpp.o
[ 71%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/reconstruct.cpp.o
[ 76%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/impl/relu.cpp.o
[ 73%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/secCompMultiParty.cpp.o
[ 78%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/snn_helper.cpp.o
[ 79%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/tools.cpp.o
[ 80%] Building CXX object modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/snn_protocol_ops.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/build.make:734: recipe for target 'modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/tools.cpp.o' failed
make[2]: *** [modules/protocol/mpc/snn/CMakeFiles/mpc-snn.dir/src/internal/tools.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....

在80%等时候，卡住

环境：
      Docker 虚拟机： ubuntu 18.04  tensorflow:1.14.0
      宿主机：Macos 10.15.7 ,内存：16 GB ，cpu: 2.2 GHz 四核Intel Core i7

**Comment by yuucyf** [comment]
**c++: internal compiler error: Killed (program cc1plus)**
先全部 clean 掉，重新编译（执行 clean_directory.sh，然后 compile_and_test_all.sh），如果还是不行应该是内存 or 磁盘空间不够的原因，那需要 check 一下你的编译环境磁盘及内存。

**Comment by vingstar** [comment]
Hi, @huajinghua, 你现在还有问题吗？如果有问题，麻烦告诉我们更多的信息；如果没有问题，我最近会关闭这个issue。
