### ISSUE TITLE
# activate protocol, use SecureNN.

### ISSUE THREAD

**Issue by YZY010203** [LatticeX-Foundation/Rosetta#45]
当执行python3 millionaire.py --party_id=0时，
在rtt.activate("SecureNN")这一句会卡住。怎么解决
![2021-01-26 09-41-23屏幕截图](https://user-images.githubusercontent.com/63569612/105788086-bd55ba80-5fba-11eb-9693-dd66d4f6a9fa.png)

**Comment by YZY010203** [comment]
![2021-01-26 09-41-23屏幕截图](https://user-images.githubusercontent.com/63569612/105788143-d9f1f280-5fba-11eb-9a12-61f8527fe112.png)

**Comment by joyoFeng** [comment]
SecureNN is a 3-PC protocol , make sure you have started the party_id=1, party_id=2 peers ?

**Comment by YZY010203** [comment]
Thank you very much,this question has been solved and then I input a number in party1,the situation become like this photo,
![2021-01-26 14-21-05屏幕截图](https://user-images.githubusercontent.com/63569612/105808158-31578900-5fe2-11eb-8d1f-f9eb6e9ba227.png)
and how to input the second number?

**Comment by joyoFeng** [comment]
> Thank you very much,this question has been solved and then I input a number in party1,the situation become like this photo,
> ![2021-01-26 14-21-05屏幕截图](https://user-images.githubusercontent.com/63569612/105808158-31578900-5fe2-11eb-8d1f-f9eb6e9ba227.png)
> and how to input the second number?

Maybe you can try the fellowing steps:
1. kill all running parties and then restart them in seperated consoles;
2. take `private_console_input(0)` for examle, you have to input the secret number in the console for party_id=0.

**Comment by YZY010203** [comment]
Thank you,the problem has been solved!

**Comment by YZY010203** [comment]
> > Thank you very much,this question has been solved and then I input a number in party1,the situation become like this photo,
> > ![2021-01-26 14-21-05屏幕截图](https://user-images.githubusercontent.com/63569612/105808158-31578900-5fe2-11eb-8d1f-f9eb6e9ba227.png)
> > and how to input the second number?
> 
> Maybe you can try the fellowing steps:
> 
>     1. kill all running parties and then restart them in seperated consoles;
> 
>     2. take `private_console_input(0)` for examle, you have to input the secret number in the console for party_id=0.

Thank you,the problem has been solved!
