### ISSUE TITLE
about the tutorial

### ISSUE THREAD

**Issue by YZY010203** [LatticeX-Foundation/Rosetta#48]
![2021-02-05 23-03-32屏幕截图](https://user-images.githubusercontent.com/63569612/107050952-d0f8f080-6806-11eb-94a0-4bdd4350868d.png)
这个 rtt-linear_regression_reveal.py 运行之前是否要进行 生成证书和key P0、P1、P2分别生成ssl服务端证书和key的操作以及编写配置文件

**Comment by vingstar** [comment]
是的，如果只是试用的话，可以参考现有的例子，直接将相关目录、文件拷贝过去就行。具体的可以参考文档 doc/DEPLOYMENT_CN.md
