### ISSUE TITLE
Excuse me,when I run the rtt-linear_regression_reveal.py,why the code cannot run correctly and the "w" cannot be printed?

### ISSUE THREAD

**Issue by YZY010203** [LatticeX-Foundation/Rosetta#50]
Excuse me,when I run the rtt-linear_regression_reveal.py,why the code cannot run correctly and the "w" cannot be printed?The result also cannot be reveal in the end.Thank you very much.
![2021-02-22 11-29-20屏幕截图](https://user-images.githubusercontent.com/63569612/108653487-87481f80-7501-11eb-985a-37f3ed5a55f8.png)
![2021-02-22 11-29-43屏幕截图](https://user-images.githubusercontent.com/63569612/108653493-8a431000-7501-11eb-80d2-e32d3c23d2c1.png)
![2021-02-22 11-29-53屏幕截图](https://user-images.githubusercontent.com/63569612/108653497-8b743d00-7501-11eb-9d06-64726c589729.png)

**Comment by vingstar** [comment]
From your snapshots about player P2, this program runs as expected.
I'm not sure what you mean that the result is incorrect. The 'weight' in source code Line 82 is printed. If you mean the the revealed_W in line 60 is not printed, please add the following just before [Line 84](https://github.com/LatticeX-Foundation/Rosetta/blob/423e2dd206bd4fa19b194cbf615cd59581f18522/example/tutorials/code/rtt-linear_regression_reveal.py#L84).

```
    W_final, b_final = sess.run([reveal_W, reveal_b])
    print(" After training, final Weight:{} \n bias:{}".format(W_final, b_final ))
```

**Comment by YZY010203** [comment]
Thank you very much!
