### ISSUE TITLE
run the millionaire program error

### ISSUE THREAD

**Issue by novaxiaohui** [LatticeX-Foundation/Rosetta#51]
when I run the quick-start program - millionare, I got "receive data from cid[0] counter:100" in all 3 terminals……  the counter is increaing by 100.
So  what's wrong with my configuration?

**Comment by vingstar** [comment]
This may be caused by some previous background process that did not exit properly, so check [this solution]( https://github.com/LatticeX-Foundation/Rosetta/issues/17#issuecomment-621324975).
