### ISSUE TITLE
Support  Python Pip Installation 

### ISSUE THREAD

**Issue by vingstar** [LatticeX-Foundation/Rosetta#52]
Python Pip installation feature.

**Comment by 00make** [comment]
I'm willing to take charge of this part of the work

**Comment by vingstar** [comment]
@00make  any progress？ need any help?

**Comment by Zizizi123** [comment]
![image](https://user-images.githubusercontent.com/38232815/126613946-256113a5-4b08-4981-ba34-fb9ecccaf828.png)
运行百万富翁实列时候 3方链接上 但是报错 求帮助  
Running millionaires ， 3-party link, but error , asking for help

**Comment by vingstar** [comment]
> ![image](https://user-images.githubusercontent.com/38232815/126613946-256113a5-4b08-4981-ba34-fb9ecccaf828.png)
> 运行百万富翁实列时候 3方链接上 但是报错 求帮助
> Running millionaires ， 3-party link, but error , asking for help

check下有没有json.CONFIG文件等问题。常见问题可以参考  https://github.com/LatticeX-Foundation/Rosetta/wiki/FAQ

**Comment by joyoFeng** [comment]
Currently, build and install from source is more stable. We are working on it in near future
