### ISSUE TITLE
Missing rtt_completion.sh

### ISSUE THREAD

**Issue by Milkve** [LatticeX-Foundation/Rosetta#54]
![image](https://user-images.githubusercontent.com/45092129/111129335-f076fc00-85b0-11eb-9bcd-e896a7c47330.png)

![image](https://user-images.githubusercontent.com/45092129/111129572-3338d400-85b1-11eb-99d0-40384c940088.png)

``` bash
-bash: rtt_completion.sh: No such file or directory
```

![image](https://user-images.githubusercontent.com/45092129/111129409-04226280-85b1-11eb-9a3c-046b24e5e28f.png)

emmm

If I use `cd Rosetta && source rtt_completion` then `./rosetta.sh compile --enable-all --enable-tests;./rosetta.sh install` I get these again:

![image](https://user-images.githubusercontent.com/45092129/111130782-92e3af00-85b2-11eb-87a1-1b8002305552.png)

**Comment by joyoFeng** [comment]
@Milkve Thank you for your issue, the issue caused by missing `rtt_completion.sh`,  actually we need `rtt_completion` instead. I've fix it: https://github.com/LatticeX-Foundation/Rosetta/commit/16ff96babbb522a402b13e62a3aaed9b70b792d8 . Try it

**Comment by Milkve** [comment]
[error.txt](https://github.com/LatticeX-Foundation/Rosetta/files/6140372/error.txt)
![image](https://user-images.githubusercontent.com/45092129/111134740-de985780-85b6-11eb-9c13-0fac6195b7f9.png)
![image](https://user-images.githubusercontent.com/45092129/111134816-f1129100-85b6-11eb-8f3b-1cc3ffd214c9.png)
![image](https://user-images.githubusercontent.com/45092129/111134907-08517e80-85b7-11eb-97c5-489c9847b513.png)
![image](https://user-images.githubusercontent.com/45092129/111134964-17383100-85b7-11eb-86b4-db12ca9b714d.png)
![image](https://user-images.githubusercontent.com/45092129/111135060-320aa580-85b7-11eb-9664-617395e757ab.png)

**Comment by Milkve** [comment]
![image](https://user-images.githubusercontent.com/45092129/111147882-ee6b6800-85c5-11eb-8185-aa0b366df65a.png)
`--recursive` after `git clone` is necessary. My fault.

**Comment by vingstar** [comment]
Yeah, we are using the git `submodule` feature, so `--recursive` is necessary in your case.
