### ISSUE TITLE
how to read the source code

### ISSUE THREAD

**Issue by YZY010203** [LatticeX-Foundation/Rosetta#55]
I have successfully run all examples in this project.Could you please tell me the correct order to learn about the project's code?

**Comment by Milkve** [comment]
Firstly, you can read the [doc](https://github.com/LatticeX-Foundation/Rosetta/tree/master/doc) and rethink how Rosetta works among parties. I'm sure that you've already know something about [customizing operations in Tensorflow](https://www.tensorflow.org/guide/create_op), and you are eagerly curious about how Rosetta replace the original operations in Tensorflow. You now can navigate the source code of Rosetta to find the [Rosetta-style integration of Privacy-Preserving Computing with TF-like operations](https://www.infoq.cn/theme/82). 
Take an operation named `matmul` as an instance, you can use it like [this](https://github.com/LatticeX-Foundation/Rosetta/blob/master/example/tutorials/code/rosetta_demo.py), and `tf.matmul` here is replaced by Rosetta, so you can use your favourite editor to navigate the source code of `matmul`. Besides, the idea of replacing `tf.matmul` is simple: writing a custom matrix multiplication operation according to Tensorflow docs, using it in your machine learning tasks and improve the code to reuse it neatly. To be concrete, if you use Rosetta, your data must be sensitive towards data safety, so implementation of the custom matrix multiplication operation follow the Privacy-Preserving computation protocols, thus assuring the theoretical and practical safety respectively. 
Moreover, if your curiousity is not only on Rosetta but also on Privacy-Preserving computation protocols, you can refer to [SecureNN](https://eprint.iacr.org/2018/442.pdf) and Rosetta's Helix. Implementations of those protocols lie in code. Those protocols provide with systematic solutions and boostinig themselves, so you can follow this repository. 
If you have little patience on comprehending safety but still have considerations on safety, you can skip the source code, and try to use Rosetta in a more complicated task like training [CIFAR-100](https://www.cs.toronto.edu/~kriz/cifar.html) and testify the safety and other performances. We are looking forward to your issues and pull requests.

**Comment by vingstar** [comment]
@YZY010203 
Just as @Milkve  said, you can start with a specific TF operator, such as `matmul`, and trace all the way from it API usage to its back-end cryptographic implementation.
BTW, the best way to learn the design and inner mechanism about Rosetta is to join us, join our community! If you are interested, please contact us. 
:-)

**Comment by YZY010203** [comment]
Thank you very much,I will learn the inner mechanism about Rosetta as you say.In addition,what should I do to join the community?

**Comment by vingstar** [comment]
> Thank you very much,I will learn the inner mechanism about Rosetta as you say.In addition,what should I do to join the community?

WELCOME! You can send direct messages to me in our [slack workspace](https://join.slack.com/t/latticexrosetta/shared_invite/zt-dum6j65d-MTxp~Bxq5OwouJW8zUKB1Q), or email me <shijunjie@matrixelements.com>.

**Comment by YZY010203** [comment]
@Milkve  When I debug the code,I face a question.Take [this demo](https://github.com/LatticeX-Foundation/Rosetta/blob/master/example/tutorials/code/rosetta_demo.py)
in an instance,to run and debug the code ,I should activate the secureNN protocol which need three nodes separately input "python demo.py --party_id=0"  in my IDE,so could you please tell me how to dubug the code and  activate the secureNN in the same time ?
Thank you very much!

**Comment by Milkve** [comment]
> @Milkve When I debug the code,I face a question.Take [this demo](https://github.com/LatticeX-Foundation/Rosetta/blob/master/example/tutorials/code/rosetta_demo.py)
> in an instance,to run and debug the code ,I should activate the secureNN protocol which need three nodes separately input "python demo.py --party_id=0" in my IDE,so could you please tell me how to dubug the code and activate the secureNN in the same time ?
> Thank you very much!

You can open three terminals in your IDE, for example, in VS Code, firstly open one bash,
![image](https://user-images.githubusercontent.com/45092129/113243164-14427d80-92e5-11eb-90dc-2e63a8240013.png)

and here you get one terminal, 
![image](https://user-images.githubusercontent.com/45092129/113243294-54a1fb80-92e5-11eb-8459-8dbe573ba46f.png)

then click the `+` to add two terminals,
![image](https://user-images.githubusercontent.com/45092129/113243333-671c3500-92e5-11eb-95a9-e2a6629cf380.png)

and now you can execute your code in three terminals.
![image](https://user-images.githubusercontent.com/45092129/113243530-c8440880-92e5-11eb-96b3-c45d6d2ba8af.png)

Another way is just using your IDE as an editer and execute code in real terminals your system provided. In Ubuntu 18.04 Desktop with default GNOME desktop, you can call out  terminal using `Ctrl` + `Alt` + `T` and the copy&paste commands in terminal turn into `Ctrl` + `Shift` + `C` and `Ctrl` + `Shift` + `V`.

If you prefer other IDE, you can also find steps to open multiple terminals in your preferred IDE similarly.
