### ISSUE TITLE
More alternative implementation for division Op

### ISSUE THREAD

**Issue by vingstar** [LatticeX-Foundation/Rosetta#57]
The current implementation of `Division` is based on idea of [Long division](https://en.wikipedia.org/wiki/Long_division). Though this can bring highest arithmetic precision, its performance may be unsatisfactory since its basic steps are performed on every bit of the ciphertext. 

So more fast alternative implementation, such as  Newton–Raphson and Goldschmidt algorithms for division, should be provided to cater to different users' need.

**Comment by Barry-ljf** [comment]
OK, I will  do this project.
