### ISSUE TITLE
Duplication of `${TF_LD_FLAGS}` in CMakeLists.txt

### ISSUE THREAD

**Issue by Milkve** [LatticeX-Foundation/Rosetta#59]
https://github.com/LatticeX-Foundation/Rosetta/blob/2a8b5115a7df9999f5a20f460a3bb5b27a6da3d7/cc/tf/secureops/CMakeLists.txt#L45
Line 45 is same as line 41, is this duplication necessary?
https://github.com/LatticeX-Foundation/Rosetta/blob/2a8b5115a7df9999f5a20f460a3bb5b27a6da3d7/cc/tf/secureops/CMakeLists.txt#L41

**Comment by vingstar** [comment]
fixed with commit #e0e29c6
