### ISSUE TITLE
I can't see logo!

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#7]
![image](https://user-images.githubusercontent.com/11187356/80331627-261cd480-887b-11ea-914b-4f3624a91525.png)

**Comment by xiexiangplaton** [comment]
That's because of the network. Global model is preferred if you are using other ways to access to the network.

**Comment by vingstar** [comment]
Hi @changjiangbailang,
We have checked this problem, and we think this is probably related to the network reachability of _\*.githubusercontent.com_ (which is used by GitHub automatically to delivery content with CDN) in some areas. We have replaced the picture from another source to alleviate this problem.

If you still can not see the logo, you may try to add some lines like `199.232.28.133    camo.githubusercontent.com` in your local `hosts` file (which is located in /etc/hosts in Mac OS, or C:\Windows\System32\drivers\etc\hosts in Windows) and refresh the pages.

Please let us know if none of the  solutions works for you.

**Comment by xiexiangplaton** [comment]
fixed
