### ISSUE TITLE
运行示例出错

### ISSUE THREAD

**Issue by ZJG0** [LatticeX-Foundation/Rosetta#73]
当我运行百万富翁问题时，在三个终端分别执行命令后会有一个或者两个终端报错。
![image](https://user-images.githubusercontent.com/24633447/120805625-94e95880-c578-11eb-93ae-df8830f03064.png)

**Comment by vingstar** [comment]
你好，
能否贴一下你的系统相关信息（OS version, Python version etc.）?方便我们复现问题。

或者：
1. 你试着通过`ulimit -c unlimited` 等方法拿到core文件;
2. 接着下载python gdb调试工具 ` sudo apt-get install gdb python3.7-dbg`
3. 假设第一步得到的文件名为 core.xxx，执行 `gdb python core.xxx`后进去执行`bt` 等调试命令，看一下core的具体上下文.

**Comment by ZJG0** [comment]
> 你好，
> 能否贴一下你的系统相关信息（OS version, Python version etc.）?方便我们复现问题。
> 
> 或者：
> 
> 1. 你试着通过`ulimit -c unlimited` 等方法拿到core文件;
> 2. 接着下载python gdb调试工具 ` sudo apt-get install gdb python3.7-dbg`
> 3. 假设第一步得到的文件名为 core.xxx，执行 `gdb python core.xxx`后进去执行`bt` 等调试命令，看一下core的具体上下文.

我使用的是docker，系统相关信息如下：
![image](https://user-images.githubusercontent.com/24633447/120878217-74a7b100-c5ed-11eb-8dcd-741d33b3aa16.png)
![image](https://user-images.githubusercontent.com/24633447/120878226-8ab57180-c5ed-11eb-9ee6-c6f7265e3e65.png)
![image](https://user-images.githubusercontent.com/24633447/120878248-aae53080-c5ed-11eb-8fc3-f25c5e4b9800.png)
![image](https://user-images.githubusercontent.com/24633447/120878254-bafd1000-c5ed-11eb-9df5-d659f8485d7c.png)
使用`ulimit -c unlimited`并下载好gdb工具后，再次运行报错，但是没拿到core文件。

**Comment by vingstar** [comment]
docker的话，会不会是docker内网络权限设置问题？

你可以搜索下怎么设置出core文件，比如具体步骤可以参考：

> 步骤一:
> ulimit -c unlimited
> 步骤二：设置core dump文件位置
> vi /etc/sysctl.conf
> 修改（添加）如下变量:
> kernel.core_pattern =core_%e_%p
> 步骤三：让修改生效
> sysctl -p/etc/sysctl.conf
> 步骤四：安装python调试工具
> sudo apt-get install gdb python3.6-dbg
> 步骤五：重新运行一次你的代码会在当前目录生成一个core.XXX文件
> 步骤六：执行gdb python core.XXX

**Comment by ZJG0** [comment]
我认为应该不是网络原因，我详细描述一下，配置好环境后开启了三个终端，每个终端都执行`python -W ignore millionaire.py --party_id={i}` 执行完前两个终端后没有错误，并且可以看到终端里出现了交互信息，当执行第三个终端命令后，应该是满足三个服务器的要求了，开始运行代码，然后就会报非法指针的错误。我接下来只能试一下core文件这个方法了。

**Comment by ZJG0** [comment]
这是core文件的上下文
![image](https://user-images.githubusercontent.com/24633447/120910136-e8f65900-c6ae-11eb-9dda-05b707fa3869.png)

**Comment by vingstar** [comment]
> 这是core文件的上下文
> ![image](https://user-images.githubusercontent.com/24633447/120910136-e8f65900-c6ae-11eb-9dda-05b707fa3869.png)

你能把你运行时各方的CONFIG.json 文件发下吗？看看是不是配置文件有错误。

**Comment by ZJG0** [comment]
![Uploading image.png…]()

**Comment by ZJG0** [comment]
![image](https://user-images.githubusercontent.com/24633447/120911200-c3218200-c6b7-11eb-9b5b-7286ad3449d0.png)

**Comment by vingstar** [comment]
看截图，`P0` 不是在（Rosetta）环境下运行？

**Comment by ZJG0** [comment]
运行的时候都是在rosetta下的，截图的这张终端重启了，没切换环境。

**Comment by vingstar** [comment]
看着是core在了 [_init_with_config](https://github.com/LatticeX-Foundation/Rosetta/blob/e0e29c6ce7d1a7b42d1ae63f24fc97e41e809926/cc/modules/protocol/mpc/comm/src/mpc_protocol.cpp#L71),  
麻烦在这个python程序代码的 `import latticex.rosetta as rtt` 之后加一句
`rtt.set_backend_loglevel(1)` , 多打些日志出来看下。

**Comment by joyoFeng** [comment]
@ZJG0 看core上下文似乎在解析后添加配置项出了问题， 请问你的机器的内存分配是否足够呢？ 可以贴出来一下吗（`free -h`）

**Comment by ZJG0** [comment]
@joyoFeng 这是内存情况：
![image](https://user-images.githubusercontent.com/24633447/120914912-8bc0ce80-c6d3-11eb-9cfb-f87c4161a51a.png)

@vingstar 这是添加语句之后的日志情况：
![image](https://user-images.githubusercontent.com/24633447/120914990-e823ee00-c6d3-11eb-8a72-0feac2b9d68c.png)

**Comment by yuucyf** [comment]
> @joyoFeng 这是内存情况：
> ![image](https://user-images.githubusercontent.com/24633447/120914912-8bc0ce80-c6d3-11eb-9cfb-f87c4161a51a.png)
> 
> @vingstar 这是添加语句之后的日志情况：
> ![image](https://user-images.githubusercontent.com/24633447/120914990-e823ee00-c6d3-11eb-8a72-0feac2b9d68c.png)
> ![image](https://user-images.githubusercontent.com/24633447/120915090-6da79e00-c6d4-11eb-8211-04a443813416.png)

现在还没有解决问题吧？
 python 版本有更新为 3.7 验证过吗？

**Comment by ZJG0** [comment]
@yuucyf python版本换成3.7后问题解决了，多谢！

**Comment by vingstar** [comment]
issue resolved.

**Comment by ZJG0** [comment]
此框架是否支持搭建卷积神经网络、全连接网络等常见的深度神经网络？如果可以的话有demo吗？

**Comment by vingstar** [comment]
可以的，可以基于现有基础Op来组装的，欢迎给我们提 PR，你也可以考虑加入我们的开发社区，共同来开发这个功能。
我们后面也会尝试加上对上层 keras 等那样的高层 API 接口的支持。

**Comment by ZJG0** [comment]
> 可以的，可以基于现有基础Op来组装的，欢迎给我们提 PR，你也可以考虑加入我们的开发社区，共同来开发这个功能。
> 我们后面也会尝试加上对上层 keras 等那样的高层 API 接口的支持。

您所说的“基于现有基础OP组装”，是否可以理解为需要完全手写神经网络的内部构造，包括手写前向传播、反向传播等。

**Comment by vingstar** [comment]
反向图不需要，SGD optimizer的自动求导我们支持了，可以参考tutorials里现有例子。
