### ISSUE TITLE
运行rosetta 版本百万富翁示例出错

### ISSUE THREAD

**Issue by jennyjue** [LatticeX-Foundation/Rosetta#74]
![image](https://user-images.githubusercontent.com/71378193/120948176-37b9f680-c774-11eb-8d3b-786fdf3d87b5.png)
三方已分别设为party_id=0，1，2连接为done后，运行./tutorials.sh rtt millionaire 会卡住一直跑不出结果，麻烦专家帮忙看看是什么原因？

**Comment by yuucyf** [comment]
> ![image](https://user-images.githubusercontent.com/71378193/120948176-37b9f680-c774-11eb-8d3b-786fdf3d87b5.png)
> 三方已分别设为party_id=0，1，2连接为done后，运行./tutorials.sh rtt millionaire 会卡住一直跑不出结果，麻烦专家帮忙看看是什么原因？

可以贴出日志我们分析分析。

另外如果你之前由于一些不当的操作导致个别 rosetta python 进程没有退出也会出现这样的情况。
你可以使用 `ps aux | grep python3` 看看系统中有多少个 rosetta python 进程在运行，使用 `killall -9 python3` 后重新跑试试。

**Comment by jennyjue** [comment]
![image](https://user-images.githubusercontent.com/71378193/120954300-73a78880-c781-11eb-913e-77494f3b4839.png)
这是party-0这边的log,按您说的命令系统中原先有4个进程，已kill后重跑但还未出结果，请问正常跑这步的时长是多久？可供我们参考一下

**Comment by yuucyf** [comment]
> ![image](https://user-images.githubusercontent.com/71378193/120954300-73a78880-c781-11eb-913e-77494f3b4839.png)
> 这是party-0这边的log,按您说的命令系统中原先有4个进程，已kill后重跑但还未出结果，请问正常跑这步的时长是多久？可供我们参考一下

如果是 rtt-millionaire 这个例程，很快的，不到 1 秒吧。

**Comment by jennyjue** [comment]
![image](https://user-images.githubusercontent.com/71378193/120956235-abb0ca80-c785-11eb-91af-ff9e78c0de20.png)
目前我们这边还是一直卡着没有结果，三台配置都是8核、16G，是配置的问题吗？

**Comment by yuucyf** [comment]
> ![image](https://user-images.githubusercontent.com/71378193/120956235-abb0ca80-c785-11eb-91af-ff9e78c0de20.png)
> 目前我们这边还是一直卡着没有结果，三台配置都是8核、16G，是配置的问题吗？

你们是在不同的机器上跑呀，那要修改配置文件，而且要保证机器间的网络能够正常连接上呀。

**Comment by jennyjue** [comment]
CONFIG文件配置都是已修改好的，三方已启动成功，矩阵乘法那个demo可以跑通，就是这个demo会一直卡住:(

**Comment by jennyjue** [comment]
![image](https://user-images.githubusercontent.com/71378193/120965475-87f68000-c797-11eb-9bac-a8b5ff73533f.png)
三方都输入了如上所示的命令，但是就还是会卡住:(

**Comment by yuucyf** [comment]
> ![image](https://user-images.githubusercontent.com/71378193/120965475-87f68000-c797-11eb-9bac-a8b5ff73533f.png)
> 三方都输入了如上所示的命令，但是就还是会卡住:(

![image](https://user-images.githubusercontent.com/45935100/120967100-af4e4c80-c799-11eb-8209-dc0b3245cca2.png)
按照图中的启动方式是一个机器中同时启动三方呀，你可以看下 `tutorials.sh` 这个脚本的内容就知道原因了。

**Comment by jennyjue** [comment]
![image](https://user-images.githubusercontent.com/71378193/120970860-9300de80-c79e-11eb-8fa1-251664dd8850.png)
我在三方各自输入这个命令可以跑出结果啦，感谢~~~

**Comment by vingstar** [comment]
issue resolved.
