### ISSUE TITLE
linear regression demo 

### ISSUE THREAD

**Issue by judywu2936** [LatticeX-Foundation/Rosetta#75]
![image](https://user-images.githubusercontent.com/85480145/120975813-3dc7cb80-c7a4-11eb-8e86-d8e585076283.png)
跑线性回归模型./tutorials.sh rtt linear_regression， 显示的sharing值与官方不同

**Comment by judywu2936** [comment]
并且结果并不会直接输出，而是需要到日志中才能查看到输出的结果。

**Comment by judywu2936** [comment]
请问是和SAVER_MODE和 RESTORE_MODE 的设置有关吗？

**Comment by ujnss** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/85480145/120975813-3dc7cb80-c7a4-11eb-8e86-d8e585076283.png)
> 跑线性回归模型./tutorials.sh rtt linear_regression， 显示的sharing值与官方不同

因为每运行一次，其随机数都是不一样的，故每次运行后的结果(sharing)与中间值都是不一样的哦~

**Comment by ujnss** [comment]
> 
> 
> 并且结果并不会直接输出，而是需要到日志中才能查看到输出的结果。

请参考 tutorials.sh，其输出被重定向到了文件，谢谢。

**Comment by judywu2936** [comment]
> > ![image](https://user-images.githubusercontent.com/85480145/120975813-3dc7cb80-c7a4-11eb-8e86-d8e585076283.png)
> > 跑线性回归模型./tutorials.sh rtt linear_regression， 显示的sharing值与官方不同
> 
> 因为每运行一次，其随机数都是不一样的，故每次运行后的结果(sharing)与中间值都是不一样的哦~

![image](https://user-images.githubusercontent.com/85480145/120984858-9ea7d180-c7ad-11eb-995d-702a8ee71af6.png)
但是官方文件里显示出的结果是数字，我这里显示的似乎是密文，这是有什么地方设置错误了吗

**Comment by ujnss** [comment]
Hi, @judywu2936, 之前文档未及时更新，现已更新。

**Comment by judywu2936** [comment]
> Hi, @judywu2936, 之前文档未及时更新，现已更新。
![image](https://user-images.githubusercontent.com/85480145/121471814-dfdcf300-c9f2-11eb-9408-9795b0f05b26.png)

好的谢谢！还有一个问题，在运行rtt-linear/logistic_regresson_saver.py文件时，输出的结果含有一段明文reveal_Y且在三方都能看见这组值，请问这个数值是什么含义？为什么在三方都能看见？

**Comment by vingstar** [comment]
> 还有一个问题，在运行rtt-linear/logistic_regresson_saver.py文件时，输出的结果含有一段明文reveal_Y且在三方都能看见这组值，请问这个数值是什么含义？为什么在三方都能看见？

这个就相当于协同预测计算任务最后的结果，恢复为明文以演示计算结束后，结果符合预期。
