### ISSUE TITLE
逻辑回归 tensorflow 与 rosetta 预测值的误差对比结果与官方demo相差较大

### ISSUE THREAD

**Issue by jennyjue** [LatticeX-Foundation/Rosetta#77]
你好，按教程记录的步骤执行到评估这步，结果如下所示：
![image](https://user-images.githubusercontent.com/71378193/121306924-02f39e00-c932-11eb-9af1-8bf4d69c34ef.png)
与官方结果：
![image](https://user-images.githubusercontent.com/71378193/121306984-1272e700-c932-11eb-9c3b-db2818328168.png)
对比相差较大，想请问下是什么原因？

**Comment by ujnss** [comment]
Hi @jennyjue, 可以参考[这里](https://github.com/LatticeX-Foundation/Rosetta/blob/master/doc/TUTORIALS_CN.md#%E9%80%BB%E8%BE%91%E5%9B%9E%E5%BD%92)，关于 `误差对比` 的说明。
