### ISSUE TITLE
组装神经网络(building NN model)

### ISSUE THREAD

**Issue by ZJG0** [LatticeX-Foundation/Rosetta#79]
我正在使用rosetta支持的op组装神经网络，在使用 `rtt.PrivateDataset(data_owner=(
    0, 1), label_owner=1).load_data(file_x, file_y, header=None)`读入数据时，样本数据维度为(55000, 784)这个没有问题，但是标签数据为one-hot编码维度为(55000, 10)，读入后缺变成了(55000, 1)。这是 `rtt.PrivateDataset`的问题吗？
![image](https://user-images.githubusercontent.com/24633447/122320932-a443ab00-cf55-11eb-8508-0fdc8cf74f8a.png)

**Comment by vingstar** [comment]
We only support the label as a 1-D vector for now:
https://github.com/LatticeX-Foundation/Rosetta/blob/7c5705798d0228ef7a9e258256b1e56875f983d6/python/latticex/rosetta/controller/dataset_api.py#L135
, I may fix this several days later.
I think you can try to bypass this issue by using `private_input` API directly for now.

**Comment by ZJG0** [comment]
Thanks for your reply. I will try the `private_input ` API. 
As above, I am trying to build a neural network with existing Ops, so ,if possible, i hope that we can maintain the issue opening or communicate through other means(email,  instant message APP etc). In addition, do you have more detailed development documents? Because, i find a few `class`s are not defined in the code given such as `DataSet` etc.

**Comment by vingstar** [comment]
Definitely! We have some open tasks, such as [Project 3](https://github.com/LatticeX-Foundation/Rosetta/projects/3) on integrating deep models in Rosetta, for community developers. 
We will release more documents for developer.
