### ISSUE TITLE
Task: Integrating secure tree inference

### ISSUE THREAD

**Issue by vingstar** [LatticeX-Foundation/Rosetta#81]
Tree models are very popular and effective in practical tasks. And native TF 1.14 also support tree-based models in its  `contrib` module , such as [contrib/tensor_forest/](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/contrib/tensor_forest) and [contrib/boosted_trees/](https://github.com/tensorflow/tensorflow/tree/r1.14/tensorflow/contrib/boosted_trees).

As the first step to support secure tree-based ML models, we will support secure inference phase of them, with the aim that users can  just use them as using the native ones.

**Comment by joyoFeng** [comment]
Tensorflow tree itegration involve a bit more work, we degrade the priority.
