### ISSUE TITLE
minor error in document

### ISSUE THREAD

**Issue by AdijeShen** [LatticeX-Foundation/Rosetta#84]
![image](https://user-images.githubusercontent.com/16702475/127813648-a1f6fc30-2c5b-4093-a955-bfdeb1fe154b.png)
in the ## source code installation chapter of doc/DEPLOYMENT.md, there is no file currently names "compile_and_test_all.sh"

should be changed into ./rosetta.sh compile --enable-protocol-mpc-securenn; ./rosetta.sh install which is the same as the README.md

**Comment by vingstar** [comment]
Thank you!
Fixed with commit #8734bb0.
