### ISSUE TITLE
debug problems: CMakeLists.txt

### ISSUE THREAD

**Issue by kaig0d** [LatticeX-Foundation/Rosetta#85]
Hello, guys! 

> I want to debug /mpc/snn separately through **cmake**, but I get into some trouble. Let me introduce these steps which I operate.

- Firstly, enter the directory : /Desktop/Rosetta-master/Rosetta-master/cc/modules/protocol/mpc/snn
- Secondly, execute some instructions:
   mkdir build
   cd build
   cmake ..

However,  errors occurred!

The fault information: 
`CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at comm/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

**CMake Error at comm/CMakeLists.txt:15 (install_libraries):
  Unknown CMake command "install_libraries".**
`
My cmake version is **3.20.5**.

**Comment by joyoFeng** [comment]
@kaig0d You cannot just compile and use mpc/snn alone as `SecureNN` module is intergrated into `Rosetta`. You can refer to
```bash
# clone rosetta git repository
git clone --recurse https://github.com/LatticeX-Foundation/Rosetta.git
cd Rosetta
# compile, install. You may check more compilation options by checking `rosetta.sh --help`
bash clean_pip; ./rosetta.sh compile --enable-protocol-mpc-securenn; ./rosetta.sh install
```
which just compile and enable SecureNN protocol as secure backend protocol.
What's more, if you wanna debug SecureNN protocol, please enable debug mode and cpp tests while compiling with following commands:
```
bash clean_pip; ./rosetta.sh compile --enable-protocol-mpc-securenn --build_type=Debug --enable-tests; ./rosetta.sh install
```
then you will find some example programs in `build/bin/` with prefix `protocol_mpc_tests_snn`, for example matmul with full name `protocol_mpc_tests_snn_matmul`.

**Comment by kaig0d** [comment]
Early reply. Thanks a lot.  

I think you have already solved my problems.
