### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by YasinZhao** [LatticeX-Foundation/Rosetta#89]
你好，我在按文档安装Rosetta时，报如下错误，请问是缺少什么组件呢（python、pip、cmake、ubuntu、tensorflow版本都符合部署要求）

/home/Rosetta/cc/modules/common/include/utils/logger_vector_ostream.h:20:10: fatal error: spdlog/fmt/ostr.h: No such file or directory
 #include "spdlog/fmt/ostr.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
run stage run_rosetta_compile_python ok.
Ready to install
stage run_rosetta_install_python.
WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
run_rosetta_install_python.

**Comment by shuihan0555** [comment]
您好, 请问子模块您是否已经拉取更新? 即cc/third_party/spdlog 目录是否有文件?如果您这边方便的话, 是否可以把完整的命令从git clone开始到编译的发出来不?

**Comment by YasinZhao** [comment]
> 您好, 请问子模块您是否已经拉取更新? 即cc/third_party/spdlog 目录是否有文件?如果您这边方便的话, 是否可以把完整的命令从git clone开始到编译的发出来不?

你好，之前本地git clone有问题，我是下载的zip包，spdlog确实缺少文件，现在已解决，谢谢~
