### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#9]
![image](https://user-images.githubusercontent.com/11187356/80332479-8745a780-887d-11ea-8f72-fba9ede52006.png)

**Comment by joyoFeng** [comment]
We are pleased to inform you that we have just fixed those spelling errors and committed to : [Rosetta](https://github.com/LatticeX-Foundation/Rosetta).  The fix commit: https://github.com/LatticeX-Foundation/Rosetta/pull/12/commits/3e49c35eaca53e40194b20696cd04cede4e5d6b4
