### ISSUE TITLE
Provide complete configuration options

### ISSUE THREAD

**Issue by strahe** [LatticeX-Foundation/Rosetta#90]
Hi， can you provide complete configuration options?
Thanks a lot.

**Comment by yuucyf** [comment]
> Hi， can you provide complete configuration options?
> Thanks a lot.

The configuration option has five sessions, NODE_INFO, DATA_NODES, COMPUTATION_NODES and RESULT_NODES.
For details, please refer to:https://github.com/LatticeX-Foundation/Rosetta-IO
