### ISSUE TITLE
the application of rosetta in  combine forecast

### ISSUE THREAD

**Issue by Averryjj** [LatticeX-Foundation/Rosetta#91]
联合预测场景中，一方有数据一方有模型

代码如下：
rtt.activate("SecureNN")
file_feature = "test_feature.csv"
错误行：cipher_feature = rtt.PrivateDataset(data_owner=(0,),dataset_type=DatasetType.FeatureAligned).load_X(file_feature)

error：Segmentation fault
/dataset_api.py  load_X（）in line137

是否load_X函数的参数传入有误，如果是请指导怎么解决

**Comment by joyoFeng** [comment]
@Averryjj 你好， 麻烦贴一下机器配置和输出日志。另外：输入文件数据是否为空呢？

**Comment by Averryjj** [comment]
![image](https://user-images.githubusercontent.com/89241701/134902891-494bb94c-756d-40c0-8a2a-74d529c32199.png)
分别在三台服务器上的Ubuntu的docker容器上运行，其他测试样例均已跑通

**Comment by Averryjj** [comment]
数据集不为空

**Comment by xiaojiqing** [comment]
存在一个bug, 已修复，用最新的代码再试试。

**Comment by Averryjj** [comment]
是说需要更新Rosetta的安装包呢？还是我的代码的问题呢？新的代码是什么意思?

**Comment by xiaojiqing** [comment]
就是现在master分支的代码，你提出这个issue后，我发现了导致这个问题的bug，修改代码提交了

**Comment by Averryjj** [comment]
load_X（）的问题解决了，谢谢，但是出现了新的问题，
<img width="517" alt="企业微信截图_16328296351162" src="https://user-images.githubusercontent.com/89241701/135080876-436669e4-dace-445b-bfec-4e94fd22f712.png">
读取的特征数据是arrary，模型参数读取的时候是使用PrivateInput()函数还是使用private_input(）函数
PrivateInput()函数读取的模型参数为tensor类型无法与load_X()读取的隐私数据进行相乘运算，如果使用private_input()怎样设置只读取p1方的参数数据呢?
![image](https://user-images.githubusercontent.com/89241701/135081659-d1b50016-ab57-45fb-bb26-0e5e831c742c.png)

这样的代码会出现P0和p2方出错，请指教哈

**Comment by xiaojiqing** [comment]
private_input和PrivateInput都只是用来输入数据，数据的shape在各方都是已知的，模型的保存和加载建议使用tf.train.Saver来save和restore, 需要使用rtt.set_saver_model和rtt.set_restore_model设置保存和加载模型的方式，具体可以参考example/tutorials/code下的rtt-linear_regression_saver.py和rtt-linear_regression_restore.py.
