### ISSUE TITLE
安装下载问题

### ISSUE THREAD

**Issue by YasinZhao** [LatticeX-Foundation/Rosetta#93]
你好，我在拉取最新代码时，spdlog子模块一直下载不下来，可否提供一个完整代码的zip包供下载，谢谢~

**Comment by shuihan0555** [comment]
> 你好，我在拉取最新代码时，spdlog子模块一直下载不下来，可否提供一个完整代码的zip包供下载，谢谢~
1. 克隆项目时, 请递归克隆
git clone --recurse https://github.com/LatticeX-Foundation/Rosetta.git
2. 克隆项目后, 请拉取子模块
git submodule update --init --recursive
NB: 请按照官网文档步骤执行, 不建议下载压缩包.

**Comment by YasinZhao** [comment]
> > 你好，我在拉取最新代码时，spdlog子模块一直下载不下来，可否提供一个完整代码的zip包供下载，谢谢~
> 
> 1. 克隆项目时, 请递归克隆
>    git clone --recurse https://github.com/LatticeX-Foundation/Rosetta.git
> 2. 克隆项目后, 请拉取子模块
>    git submodule update --init --recursive
>    NB: 请按照官网文档步骤执行, 不建议下载压缩包.

你好，这两种方法之前就已经试过了，还是拉取不了spdlog子模块，我现在用了之前下载的老代码先运行着，感谢回复了

**Comment by yuucyf** [comment]
> 你好，我在拉取最新代码时，spdlog子模块一直下载不下来，可否提供一个完整代码的zip包供下载，谢谢~

网络的问题。
参考 https://github.com/LatticeX-Foundation/Rosetta/issues/96
