### ISSUE TITLE
隐私数据输入

### ISSUE THREAD

**Issue by Averryjj** [LatticeX-Foundation/Rosetta#94]
X= rtt.private_input(1,X)
只有节点1有X数据，节点0和节点2无X数据，为None
运行时节点0和节点2出现
<img width="673" alt="企业微信截图_1633682717519" src="https://user-images.githubusercontent.com/89241701/136526489-158217db-eddc-4738-9b65-91685f3c7dc1.png">

private_input()函数不是指定了节点了吗，为什么还是会去读取其他节点中X的信息，导致出错，求指教

**Comment by xiaojiqing** [comment]
rtt.private_input要求没有数据的节点也要知道数据的shape，这个函数只是单纯完成secret sharing，不像PrivateDataset在secret sharing前会同步shape信息。只有节点1有数据，只要节点1写真实的数据，节点0和节点2写假的数据就好了，但3个节点的shape要保持一致，或者可以使用rtt.private_console_input输入数据，3个节点就可以运行相同的脚本了，可以参考example/tutorials/code下的rtt-matmul.py和rtt-matmul-console.py.
