### ISSUE TITLE
现在Rosetta能支持加密通信吗？代码中包含ssl部分的代码，但是在python中无法开启加密数据传输。

### ISSUE THREAD

**Issue by lordofkey** [LatticeX-Foundation/Rosetta#95]
现在Rosetta能支持加密通信吗？代码中包含ssl部分的代码，但是在python中无法开启加密数据传输。

**Comment by shenpeilin** [comment]
> 

这个居然是没有的吗？为什么在部署指南里有生成ssl证书的步骤呢？这个证书用来干嘛呢？

**Comment by xiangxiecrypto** [comment]
> > 
> 
> 这个居然是没有的吗？为什么在部署指南里有生成ssl证书的步骤呢？这个证书用来干嘛呢？

这是存量的的代码没有完全清理，如果有SSL的需求，建议使用自定义的通信模块来替换
