### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by OPilgrim** [LatticeX-Foundation/Rosetta#96]
I followed the README.md step by step, but the following errors still occurred when I executed   `./rosetta.sh compile --enable-protocol-mpc-securenn`. Can you give me some advice? Thank you very much!

```
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
TF_INCS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include
TF_LIBS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow
TF_CFLG ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1']
TF_LFLG ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1']
--------------------------------------------------------------------------------
extra_lflags ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1', '-Wl,-rpath=$ORIGIN']
extra_cflags ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1', '-DSML_USE_UINT64=1', '-fPIC', '-Wno-unused-function', '-Wno-sign-compare', '-std=c++11']
library_dirs ['.', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', './build/lib']
include_dirs ['/home/pilgrim/Rosetta', '.', 'include', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '/home/pilgrim/Rosetta/cc/modules/common/include', '/home/pilgrim/Rosetta/cc/modules/common/include/utils', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src', '/home/pilgrim/Rosetta/cc/modules/protocol/public', '/home/pilgrim/Rosetta/cc/third_party/rapidjson/include', '/home/pilgrim/Rosetta/cc/third_party/pybind11/include', '/home/pilgrim/Rosetta/cc/third_party/spdlog/include', '/home/pilgrim/Rosetta/cc/third_party/io/include']
running bdist_wheel
running build
running build_py
running egg_info
writing python/latticex_rosetta.egg-info/PKG-INFO
writing dependency_links to python/latticex_rosetta.egg-info/dependency_links.txt
writing requirements to python/latticex_rosetta.egg-info/requires.txt
writing top-level names to python/latticex_rosetta.egg-info/top_level.txt
reading manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/latticex/*.so*'
warning: no files found matching 'python/latticex/lib128/*.so*'
no previously-included directories found matching 'python/latticex/rosetta/mpc/*/test_cases'
warning: no previously-included files matching 'test_mpc*.py' found anywhere in distribution
adding license file 'COPYING.LESSER'
writing manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
running build_ext
building 'latticex/_rosetta' extension
gcc -pthread -B /home/pilgrim/miniconda3/envs/python36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pilgrim/Rosetta -I. -Iinclude -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -I/home/pilgrim/Rosetta/cc/modules/common/include -I/home/pilgrim/Rosetta/cc/modules/common/include/utils -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src -I/home/pilgrim/Rosetta/cc/modules/protocol/public -I/home/pilgrim/Rosetta/cc/third_party/rapidjson/include -I/home/pilgrim/Rosetta/cc/third_party/pybind11/include -I/home/pilgrim/Rosetta/cc/third_party/spdlog/include -I/home/pilgrim/Rosetta/cc/third_party/io/include -I/home/pilgrim/miniconda3/envs/python36/include/python3.6m -c cc/python_export/_rosetta.cc -o build/temp.linux-x86_64-3.6/cc/python_export/_rosetta.o -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -DSML_USE_UINT64=1 -fPIC -Wno-unused-function -Wno-sign-compare -std=c++11
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/pilgrim/Rosetta/cc/modules/iowrapper/include/io_wrapper.h:22,
                 from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_base.h:23,
                 from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_manager.h:3,
                 from /home/pilgrim/Rosetta/cc/python_export/input.h:33,
                 from cc/python_export/_rosetta.cc:24:
/home/pilgrim/Rosetta/cc/modules/common/include/utils/rtt_logger.h:24:10: fatal error: spdlog/loggers.h: No such file or directory
   24 | #include "spdlog/loggers.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
run stage run_rosetta_compile_python ok.
```

**Comment by yuucyf** [comment]
> I followed the README.md step by step, but the following errors still occurred when I executed `./rosetta.sh compile --enable-protocol-mpc-securenn`. Can you give me some advice? Thank you very much!
> 
> ```
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> TF_INCS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include
> TF_LIBS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow
> TF_CFLG ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1']
> TF_LFLG ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1']
> --------------------------------------------------------------------------------
> extra_lflags ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1', '-Wl,-rpath=$ORIGIN']
> extra_cflags ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1', '-DSML_USE_UINT64=1', '-fPIC', '-Wno-unused-function', '-Wno-sign-compare', '-std=c++11']
> library_dirs ['.', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', './build/lib']
> include_dirs ['/home/pilgrim/Rosetta', '.', 'include', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '/home/pilgrim/Rosetta/cc/modules/common/include', '/home/pilgrim/Rosetta/cc/modules/common/include/utils', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src', '/home/pilgrim/Rosetta/cc/modules/protocol/public', '/home/pilgrim/Rosetta/cc/third_party/rapidjson/include', '/home/pilgrim/Rosetta/cc/third_party/pybind11/include', '/home/pilgrim/Rosetta/cc/third_party/spdlog/include', '/home/pilgrim/Rosetta/cc/third_party/io/include']
> running bdist_wheel
> running build
> running build_py
> running egg_info
> writing python/latticex_rosetta.egg-info/PKG-INFO
> writing dependency_links to python/latticex_rosetta.egg-info/dependency_links.txt
> writing requirements to python/latticex_rosetta.egg-info/requires.txt
> writing top-level names to python/latticex_rosetta.egg-info/top_level.txt
> reading manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'python/latticex/*.so*'
> warning: no files found matching 'python/latticex/lib128/*.so*'
> no previously-included directories found matching 'python/latticex/rosetta/mpc/*/test_cases'
> warning: no previously-included files matching 'test_mpc*.py' found anywhere in distribution
> adding license file 'COPYING.LESSER'
> writing manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
> running build_ext
> building 'latticex/_rosetta' extension
> gcc -pthread -B /home/pilgrim/miniconda3/envs/python36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pilgrim/Rosetta -I. -Iinclude -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -I/home/pilgrim/Rosetta/cc/modules/common/include -I/home/pilgrim/Rosetta/cc/modules/common/include/utils -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src -I/home/pilgrim/Rosetta/cc/modules/protocol/public -I/home/pilgrim/Rosetta/cc/third_party/rapidjson/include -I/home/pilgrim/Rosetta/cc/third_party/pybind11/include -I/home/pilgrim/Rosetta/cc/third_party/spdlog/include -I/home/pilgrim/Rosetta/cc/third_party/io/include -I/home/pilgrim/miniconda3/envs/python36/include/python3.6m -c cc/python_export/_rosetta.cc -o build/temp.linux-x86_64-3.6/cc/python_export/_rosetta.o -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -DSML_USE_UINT64=1 -fPIC -Wno-unused-function -Wno-sign-compare -std=c++11
> cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/pilgrim/Rosetta/cc/modules/iowrapper/include/io_wrapper.h:22,
>                  from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_base.h:23,
>                  from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_manager.h:3,
>                  from /home/pilgrim/Rosetta/cc/python_export/input.h:33,
>                  from cc/python_export/_rosetta.cc:24:
> /home/pilgrim/Rosetta/cc/modules/common/include/utils/rtt_logger.h:24:10: fatal error: spdlog/loggers.h: No such file or directory
>    24 | #include "spdlog/loggers.h"
>       |          ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> run stage run_rosetta_compile_python ok.
> ```

You need to get down the submodules that  dependent on the project.
Use the following commands：
> git submodule init
> git submodule update

**Comment by OPilgrim** [comment]
> > I followed the README.md step by step, but the following errors still occurred when I executed `./rosetta.sh compile --enable-protocol-mpc-securenn`. Can you give me some advice? Thank you very much!
> > ```
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   np_resource = np.dtype([("resource", np.ubyte, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> > /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> >   np_resource = np.dtype([("resource", np.ubyte, 1)])
> > TF_INCS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include
> > TF_LIBS /home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow
> > TF_CFLG ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1']
> > TF_LFLG ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1']
> > --------------------------------------------------------------------------------
> > extra_lflags ['-L/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', '-l:libtensorflow_framework.so.1', '-Wl,-rpath=$ORIGIN']
> > extra_cflags ['-I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=1', '-DSML_USE_UINT64=1', '-fPIC', '-Wno-unused-function', '-Wno-sign-compare', '-std=c++11']
> > library_dirs ['.', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow', './build/lib']
> > include_dirs ['/home/pilgrim/Rosetta', '.', 'include', '/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include', '/home/pilgrim/Rosetta/cc/modules/common/include', '/home/pilgrim/Rosetta/cc/modules/common/include/utils', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include', '/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src', '/home/pilgrim/Rosetta/cc/modules/protocol/public', '/home/pilgrim/Rosetta/cc/third_party/rapidjson/include', '/home/pilgrim/Rosetta/cc/third_party/pybind11/include', '/home/pilgrim/Rosetta/cc/third_party/spdlog/include', '/home/pilgrim/Rosetta/cc/third_party/io/include']
> > running bdist_wheel
> > running build
> > running build_py
> > running egg_info
> > writing python/latticex_rosetta.egg-info/PKG-INFO
> > writing dependency_links to python/latticex_rosetta.egg-info/dependency_links.txt
> > writing requirements to python/latticex_rosetta.egg-info/requires.txt
> > writing top-level names to python/latticex_rosetta.egg-info/top_level.txt
> > reading manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
> > reading manifest template 'MANIFEST.in'
> > warning: no files found matching 'python/latticex/*.so*'
> > warning: no files found matching 'python/latticex/lib128/*.so*'
> > no previously-included directories found matching 'python/latticex/rosetta/mpc/*/test_cases'
> > warning: no previously-included files matching 'test_mpc*.py' found anywhere in distribution
> > adding license file 'COPYING.LESSER'
> > writing manifest file 'python/latticex_rosetta.egg-info/SOURCES.txt'
> > running build_ext
> > building 'latticex/_rosetta' extension
> > gcc -pthread -B /home/pilgrim/miniconda3/envs/python36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pilgrim/Rosetta -I. -Iinclude -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -I/home/pilgrim/Rosetta/cc/modules/common/include -I/home/pilgrim/Rosetta/cc/modules/common/include/utils -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/include -I/home/pilgrim/Rosetta/cc/modules/protocol/mpc/snn/src -I/home/pilgrim/Rosetta/cc/modules/protocol/public -I/home/pilgrim/Rosetta/cc/third_party/rapidjson/include -I/home/pilgrim/Rosetta/cc/third_party/pybind11/include -I/home/pilgrim/Rosetta/cc/third_party/spdlog/include -I/home/pilgrim/Rosetta/cc/third_party/io/include -I/home/pilgrim/miniconda3/envs/python36/include/python3.6m -c cc/python_export/_rosetta.cc -o build/temp.linux-x86_64-3.6/cc/python_export/_rosetta.o -I/home/pilgrim/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -DSML_USE_UINT64=1 -fPIC -Wno-unused-function -Wno-sign-compare -std=c++11
> > cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> > In file included from /home/pilgrim/Rosetta/cc/modules/iowrapper/include/io_wrapper.h:22,
> >                  from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_base.h:23,
> >                  from /home/pilgrim/Rosetta/cc/modules/protocol/public/include/protocol_manager.h:3,
> >                  from /home/pilgrim/Rosetta/cc/python_export/input.h:33,
> >                  from cc/python_export/_rosetta.cc:24:
> > /home/pilgrim/Rosetta/cc/modules/common/include/utils/rtt_logger.h:24:10: fatal error: spdlog/loggers.h: No such file or directory
> >    24 | #include "spdlog/loggers.h"
> >       |          ^~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > error: command 'gcc' failed with exit status 1
> > run stage run_rosetta_compile_python ok.
> > ```
> 
> You need to get down the submodules that dependent on the project. Use the following commands：
> 
> > git submodule init
> > git submodule update

This method works and Rosetta has been installed successfully. Thank you very much!

**Comment by junjiequ123** [comment]
Noticed git has personal access token upgrade, suggest to amend README to make sure git submodule update --init got executed
