### ISSUE TITLE
请问Rossetta的底层通信是什么？在代码里是如何体现的？

### ISSUE THREAD

**Issue by shenpeilin** [LatticeX-Foundation/Rosetta#97]
我在部署文档里了解到部署过程中有配置ssl证书的步骤，但在之前其他人问的问题中，又看到了有关不支持加密通信的回答

想请教一下底层的通信究竟是否是基于ssl加密的呢？如果不是的话，配置证书的意义是什么呢？

**Comment by yuucyf** [comment]
> 我在部署文档里了解到部署过程中有配置ssl证书的步骤，但在之前其他人问的问题中，又看到了有关不支持加密通信的回答
> 
> 想请教一下底层的通信究竟是否是基于ssl加密的呢？如果不是的话，配置证书的意义是什么呢？

目前 Rosetta 不支持 SSL，至于部署文档中为什么会有配置证书的内容，那是由于早期版本有支持 SSL，后面会更新部署文档进行同步。

**Comment by shenpeilin** [comment]
早期支持了后期又取消了是基于什么考虑呢？ssl通信按道理来说应该是很有必要的功能啊

**Comment by yuucyf** [comment]
> 早期支持了后期又取消了是基于什么考虑呢？ssl通信按道理来说应该是很有必要的功能啊

我们专注于密码协议而不是网络 IO。
