### ISSUE TITLE
代码执行异常退出后，底层协议无法重新建立连接

### ISSUE THREAD

**Issue by tiefan** [LatticeX-Foundation/Rosetta#99]
如果3个节点上使能SecureNN后，运行代码过程中发生异常中断后，重新启动Rosetta框架后底层协议无法建立连接。
log日志停在如下：
![lQLPDhrnZkvO69ZnzQKNsNZnxhev54syAaheLs8AVQA_653_103](https://user-images.githubusercontent.com/12456214/145747311-edc6459a-6f25-41b5-a0ad-42f383ec1948.jpg)
经过试验，换端口后可以再次建立连接，所以怀疑退出后哪块程序还在占用tcp端口资源。
讨教一下，有没有什么规避的方法？

**Comment by yuucyf** [comment]
> 如果3个节点上使能SecureNN后，运行代码过程中发生异常中断后，重新启动Rosetta框架后底层协议无法建立连接。 log日志停在如下： ![lQLPDhrnZkvO69ZnzQKNsNZnxhev54syAaheLs8AVQA_653_103](https://user-images.githubusercontent.com/12456214/145747311-edc6459a-6f25-41b5-a0ad-42f383ec1948.jpg) 经过试验，换端口后可以再次建立连接，所以怀疑退出后哪块程序还在占用tcp端口资源。 讨教一下，有没有什么规避的方法？

这种情况应该是异常过程中有的节点还在，你使用 grep 看一下进程中是不是还有其他节点，如果还在 kill 掉重新跑即可，无需换端口。

**Comment by tiefan** [comment]
> > 如果3个节点上使能SecureNN后，运行代码过程中发生异常中断后，重新启动Rosetta框架后底层协议无法建立连接。 log日志停在如下： ![lQLPDhrnZkvO69ZnzQKNsNZnxhev54syAaheLs8AVQA_653_103](https://user-images.githubusercontent.com/12456214/145747311-edc6459a-6f25-41b5-a0ad-42f383ec1948.jpg) 经过试验，换端口后可以再次建立连接，所以怀疑退出后哪块程序还在占用tcp端口资源。 讨教一下，有没有什么规避的方法？
> 
> 这种情况应该是异常发生后有的节点还在，你使用 grep 看一下进程中是不是还有其他节点，如果还在 kill 掉重新跑即可，无需换端口。

看了一下，确实有进程残留，杀死后就可以了，感谢
